import {NextRequest,NextResponse} from 'next/server';
import {calculateQuotes,LogisticsInput,extractCity,matchLogisticsProviders,selectDefaultLogisticsProvider,buildVehicleFreightOptions,calculateSmartDispatchEta} from '@/lib/logistics';
import {listLogisticsProviders} from '@/lib/proDb';
import { getOpenRouteServiceRoute } from '@/lib/routeService';
export const dynamic='force-dynamic';export const revalidate=0;
type Provider={name:string;address?:string;phone?:string;website?:string;rating?:number;source:string};
async function searchTransporters(input:LogisticsInput):Promise<Provider[]>{const key=process.env.SERPAPI_KEY;if(!key)return[];try{const pickup=extractCity(input.pickup);const drop=extractCity(input.drop);const url=new URL('https://serpapi.com/search');url.searchParams.set('engine','google_maps');url.searchParams.set('q',`${input.product} metal transport logistics ${pickup} to ${drop}`);url.searchParams.set('api_key',key);url.searchParams.set('hl','en');url.searchParams.set('gl','in');const res=await fetch(url.toString(),{next:{revalidate:1800}});if(!res.ok)return[];const data=await res.json();return (data.local_results||[]).slice(0,8).map((r:any)=>({name:r.title,address:r.address,phone:r.phone,website:r.website,rating:r.rating,source:'SerpApi Google Maps'}));}catch{return[]}}
function publicProvider(row:any){const{adminNotes,panNumber,raw,...safe}=row;return safe;}
export async function GET(req:NextRequest){const providers=await listLogisticsProviders();const q=req.nextUrl.searchParams;const country=q.get('country')||'India',state=q.get('state')||'',city=q.get('city')||'',serviceType=q.get('serviceType')||'';let rows=providers.filter((p:any)=>p.status==='ACTIVE'||p.status==='PENDING_CONTRACT');if(country)rows=rows.filter((p:any)=>(p.serviceableCountries||[]).includes(country)||p.country===country);if(state)rows=rows.filter((p:any)=>(p.serviceableStates||[]).map((x:string)=>x.toLowerCase()).includes(state.toLowerCase())||String(p.state||'').toLowerCase()===state.toLowerCase());if(city)rows=rows.filter((p:any)=>[p.city,...(p.nearbyCities||[]),...(p.serviceableCities||[])].map((x:string)=>String(x).toLowerCase()).includes(city.toLowerCase()));if(serviceType)rows=rows.filter((p:any)=>[...(p.serviceTypes||[]),...(p.specializations||[])].some((x:string)=>String(x).toLowerCase().includes(serviceType.toLowerCase())));return NextResponse.json({ok:true,providers:rows.map(publicProvider),updatedAt:new Date().toISOString(),storage:process.env.DATABASE_URL?'database':'json-fallback'});}
export async function POST(req:NextRequest){try{const body=await req.json();const input:LogisticsInput={pickup:String(body.pickup||'Pune, Maharashtra'),drop:String(body.drop||'Mumbai, Maharashtra'),metal:String(body.metal||'Steel'),product:String(body.product||'TMT Bars'),weightMt:Math.max(.1,Number(body.weightMt||5)),lengthFt:Math.max(1,Number(body.lengthFt||12)),widthFt:Math.max(1,Number(body.widthFt||4)),heightFt:Math.max(1,Number(body.heightFt||4)),urgent:Boolean(body.urgent),loadingType:String(body.loadingType||'Forklift / crane available')};const quotes=calculateQuotes(input);const providers=await listLogisticsProviders();const roadRoute=await getOpenRouteServiceRoute({pickupLat:body.pickupLat,pickupLng:body.pickupLng,dropLat:body.dropLat,dropLng:body.dropLng});const routePatch=roadRoute&&roadRoute.ok?{routeDistanceKmOverride:roadRoute.distanceKm,routeDurationMinutesOverride:roadRoute.durationMinutes}:{ };const matchInput={pickup:input.pickup,drop:input.drop,weightMt:input.weightMt,product:input.product,serviceType:body.serviceType,date:body.date,paymentResponsibility:body.paymentResponsibility,dispatchReadiness:body.dispatchReadiness,pickupLat:body.pickupLat,pickupLng:body.pickupLng,dropLat:body.dropLat,dropLng:body.dropLng,...routePatch};const matches=matchLogisticsProviders(matchInput,providers).map((m:any)=>({...m,provider:publicProvider(m.provider)}));const vehicleOptions=buildVehicleFreightOptions(matchInput as any,providers).map((o:any)=>({...o,providerName:o.providerName,adminPricingLocked:true}));const def=selectDefaultLogisticsProvider(matchInput,providers);const eta=calculateSmartDispatchEta({pickup:input.pickup,drop:input.drop,dispatchReadiness:body.dispatchReadiness,productionLeadTime:body.productionLeadTime,deliveryEta:body.deliveryEta,readyDispatchTime:body.readyDispatchTime,pickupLat:body.pickupLat,pickupLng:body.pickupLng,dropLat:body.dropLat,dropLng:body.dropLng,...routePatch});const live=await searchTransporters(input);return NextResponse.json({success:true,input,checkedAt:new Date().toISOString(),mode:'Location-aware logistics matching + vehicle freight calculation',route:roadRoute,disclaimer:'Admin controls final logistics pricing because vendors are external partners. Vehicle rate/km, minimum freight, loading, insurance, GST and payment responsibility are recalculated server-side before checkout/invoice.',eta,quotes,vehicleOptions,providers:live,matches,defaultAssignment:def?{...def,provider:publicProvider(def.provider)}:null});}catch(e){console.error('LOGISTICS_QUOTE_ERROR',e);return NextResponse.json({success:false,error:'Unable to calculate logistics quote.'},{status:500})}}
