'use client';
import { useEffect, useMemo, useState } from 'react';
import { indiaLocations, getCitiesForState } from '@/lib/indiaLocations';
import { productCategories } from '@/lib/marketplaceData';
import LocationPinPicker from '@/components/LocationPinPicker';
import ContextualHelpBox from '@/components/help/ContextualHelpBox';


async function readFiles(files: FileList | null){
  if(!files) return {names:[], gallery:[] as any[]};
  const list = Array.from(files).slice(0,6);
  const gallery = await Promise.all(list.map((file)=>new Promise<any>((resolve)=>{
    if(!file.type.startsWith('image/')) return resolve({name:file.name,type:file.type,size:file.size});
    const reader = new FileReader();
    reader.onload = ()=> resolve({name:file.name,type:file.type,size:file.size,dataUrl:String(reader.result||'')});
    reader.onerror = ()=> resolve({name:file.name,type:file.type,size:file.size});
    reader.readAsDataURL(file);
  })));
  return {names:list.map(f=>f.name), gallery};
}

const intents = [['BUY','I want to buy / source material'],['SELL','I want to sell / list ready stock'],['SCRAP','I want to buy/sell scrap'],['LOGISTICS','I need transport / delivery support']];
function deliveryEstimate(form:any) { const ready = form.dispatchReadiness === 'READY_STOCK'; const road = form.roadTransitDays || '1-3 days road transit after pickup'; if (form.intent !== 'SELL') return form.deliveryTime || road; if (ready) return `${form.readyDispatchTime || 'Ready dispatch after confirmation'} + ${road}`; return `${form.productionLeadTime || 'Production/procurement time to confirm'} + road transit will be calculated after pickup city confirmation`; }

export default function RequirementForm({ initialIntent = 'BUY' }: { initialIntent?: string }) {
  const [form, setForm] = useState<any>({intent:initialIntent, metal:'Steel', product:'TMT bars', grade:'Fe 500D', unit:'MT', state:'Maharashtra', city:'Pune', pickupAddress:'', pickupLat:'', pickupLng:'', pickupMapUrl:'', dispatchReadiness:'READY_STOCK', roadTransitDays:'1-3 days road transit'});
  const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); const [pinMessage, setPinMessage] = useState(''); const [user,setUser]=useState<any>(null);
  const selected = useMemo(()=>productCategories.find(x=>x.metal===form.metal) || productCategories[0], [form.metal]);
  const contextualHelpType = form.intent === 'SELL' ? 'sellerOnboarding' : 'postRequirement';
  const cities = getCitiesForState(form.state); const set = (k:string,v:any)=>setForm((f:any)=>({...f,[k]:v}));
  useEffect(() => { try{const u=JSON.parse(localStorage.getItem('talmech-user')||'null'); setUser(u); if(u){setForm((f:any)=>({...f,companyName:u.firmName||u.company||'',contactName:u.ownerName||u.name||'',phone:u.primaryMobile||u.phone||'',email:u.email||''}));}}catch{} const params = new URLSearchParams(window.location.search); const metalSlug = params.get('metal'); const product = params.get('product'); if (metalSlug || product) { const bySlug = productCategories.find((m) => m.slug === metalSlug); const byProduct = productCategories.find((m) => m.products.some((p) => p.toLowerCase() === String(product || '').toLowerCase())); const m = bySlug || byProduct; if (m) setForm((f:any) => ({...f, metal:m.metal, product: product || m.products[0], grade:m.grades[0]})); } }, []);
  async function pinLookup(pin: string) { set('pincode', pin); const clean = pin.replace(/\D/g,'').slice(0,6); if (clean.length !== 6) { setPinMessage(''); return; } try { const d = await fetch(`/api/pincode?pin=${clean}`).then(r=>r.json()); if (d.ok && d.info) { setForm((f:any)=>({...f,pincode:clean,state:d.info.state,city:d.info.city,area:f.area || d.info.area,locationRegion:d.info.region})); setPinMessage(`Auto-detected: ${d.info.area}, ${d.info.city}, ${d.info.state}`); } else { setPinMessage('PIN not in local sample database. Select state/city manually; admin will verify exact area before matching.'); } } catch { setPinMessage('PIN lookup unavailable. Please select state and city.'); } }
  async function handleFiles(files: FileList | null) { const {names,gallery}=await readFiles(files); setForm((f:any)=>({...f,mediaFileNames:names,mediaGallery:gallery})); }
  async function submit(e: React.FormEvent) { e.preventDefault(); setSaving(true); setMessage(''); const mediaLinks = String(form.mediaLinks || '').split('\n').map((x) => x.trim()).filter(Boolean); const mediaFileNames = Array.isArray(form.mediaFileNames) ? form.mediaFileNames : []; if (mediaLinks.length + mediaFileNames.length < 2) { setSaving(false); setMessage('Please add at least 2 product images, drawing links, test certificate links, or document filenames. This is required for safer trading verification.'); return; } const payload = {...form, address: form.pickupAddress || form.address || '', mediaLinks:[...mediaLinks, ...mediaFileNames], mediaGallery: form.mediaGallery || [], deliveryEta: deliveryEstimate(form)}; const res = await fetch('/api/public-requirements', {method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify(payload)}); const data = await res.json(); setSaving(false); setMessage(data.ok ? `Submitted successfully. Reference: ${data.lead.id}. Confirmation email is sent/queued and our team will verify details before matching.` : 'Unable to save requirement. Please try again.'); if (data.ok) setForm((f:any)=>({...f, companyName:'', contactName:'', phone:'', email:'', quantity:'', targetPrice:'', technicalDetails:'', mediaLinks:'', mediaFileNames:[], mediaGallery:[]})); }
  if(!user || user.status !== 'APPROVED') return <section className="section"><div className="container"><div className="panel authRequiredPanel"><span className="eyebrow">Verified account required</span><h2>Complete Talmech account verification before posting.</h2><p className="muted">To reduce fake enquiries and protect buyers and sellers, posting access opens only after GST, mobile, address, shop images and location details are reviewed by the admin team.</p><ContextualHelpBox type={contextualHelpType} label="Need help onboarding?" /><div className="row" style={{justifyContent:'flex-start'}}><a className="btn" href="/signin">Create / check account</a><a className="btn secondary" href="/public-marketplace">Browse marketplace</a><a className="btn dark" href="/how-it-works">How it works</a></div></div></div></section>;
  return <form className="panel formGrid refinedForm" onSubmit={submit}>
    <div className="span2"><span className="eyebrow">Verified buy / sell / scrap / logistics requirement</span><h2>Post your requirement. Talmech will match local-first supply, demand and logistics.</h2><p className="muted">Add grade, quantity, PIN code, readiness, technical details and at least two product documents/images. Your confirmation is emailed to you; contact details remain inside Talmech's protected CRM.</p><ContextualHelpBox type={contextualHelpType} label={form.intent === 'SELL' ? 'Seller guide' : 'Buyer guide'} /></div>
    <label>Requirement type<select value={form.intent} onChange={e=>set('intent',e.target.value)}>{intents.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
    <label>Metal / category<select value={form.metal} onChange={e=>{const m=productCategories.find(x=>x.metal===e.target.value)!; setForm((f:any)=>({...f,metal:m.metal,product:m.products[0],grade:m.grades[0]}));}}>{productCategories.map(m=><option key={m.slug}>{m.metal}</option>)}</select></label>
    <label>Product<select value={form.product} onChange={e=>set('product',e.target.value)}>{selected.products.map(x=><option key={x}>{x}</option>)}</select></label>
    <label>Grade / quality<select value={form.grade} onChange={e=>set('grade',e.target.value)}>{selected.grades.map(x=><option key={x}>{x}</option>)}</select></label>
    <label>Quantity<input className="input" required value={form.quantity||''} onChange={e=>set('quantity',e.target.value)} placeholder="Example: 2.5" /></label><label>Unit<select value={form.unit} onChange={e=>set('unit',e.target.value)}><option>KG</option><option>MT</option><option>Nos</option><option>Bundle</option><option>Lot</option></select></label>
    <label>PIN code<input className="input" value={form.pincode||''} onChange={e=>pinLookup(e.target.value)} placeholder="411026" /></label><label>State<select value={form.state} onChange={e=>{const first=getCitiesForState(e.target.value)[0]||'';setForm((f:any)=>({...f,state:e.target.value,city:first}));}}>{indiaLocations.map(x=><option key={x.state}>{x.state}</option>)}</select></label>
    <label>City / industrial area<select value={form.city} onChange={e=>set('city',e.target.value)}>{cities.map(c=><option key={c}>{c}</option>)}</select></label><label>Area / village / MIDC / GIDC<input className="input" value={form.area||''} onChange={e=>set('area',e.target.value)} placeholder="Chakan MIDC, Bhosari, village name etc." /></label>{pinMessage && <p className="span2 notice slimNotice">{pinMessage}</p>}<div className="span2"><LocationPinPicker label={form.intent === 'SELL' ? 'Seller pickup pin / stockyard gate' : 'Buyer delivery pin / requirement location'} address={form.pickupAddress || form.address || ''} lat={form.pickupLat} lng={form.pickupLng} mapUrl={form.pickupMapUrl} city={form.city} state={form.state} onChange={(patch)=>setForm((f:any)=>({...f,pickupAddress:patch.address ?? f.pickupAddress,pickupLat:patch.lat ?? f.pickupLat,pickupLng:patch.lng ?? f.pickupLng,pickupMapUrl:patch.mapUrl ?? f.pickupMapUrl}))} help="Select exact gate / warehouse / unloading point. This pin is used for seller-to-buyer logistics distance, ETA and freight calculation." /></div>
    {form.intent === 'SELL' && <><label>Stock readiness<select value={form.dispatchReadiness} onChange={e=>set('dispatchReadiness',e.target.value)}><option value="READY_STOCK">Ready in stock / ready to dispatch</option><option value="MAKE_TO_ORDER">Need order / production required</option></select></label><label>{form.dispatchReadiness==='READY_STOCK'?'Ready dispatch time':'Production / procurement lead time'}<input className="input" value={form.dispatchReadiness==='READY_STOCK' ? (form.readyDispatchTime||'') : (form.productionLeadTime||'')} onChange={e=>set(form.dispatchReadiness==='READY_STOCK'?'readyDispatchTime':'productionLeadTime',e.target.value)} placeholder={form.dispatchReadiness==='READY_STOCK'?'Same day, 24 hours, 2 days':'7 days, 15 days, 30 days'} /></label></>}
    <label>Estimated road transit<input className="input" value={form.roadTransitDays||''} onChange={e=>set('roadTransitDays',e.target.value)} placeholder="1-3 days road transit" /></label><label>Expected quote / target rate<input className="input" value={form.targetPrice||''} onChange={e=>set('targetPrice',e.target.value)} placeholder="Optional; final rate after verification" /></label>
    <label>Company name<input className="input" required value={form.companyName||''} onChange={e=>set('companyName',e.target.value)} placeholder="Company / trader / buyer name" /></label><label>Contact person<input className="input" value={form.contactName||''} onChange={e=>set('contactName',e.target.value)} placeholder="Name" /></label><label>Phone / WhatsApp<input className="input" required value={form.phone||''} onChange={e=>set('phone',e.target.value)} placeholder="Mobile number" /></label><label>Email<input className="input" type="email" required value={form.email||''} onChange={e=>set('email',e.target.value)} placeholder="Email for confirmation" /></label>
    <label className="span2">Technical details, drawing link, size, tolerance, payment terms<textarea required value={form.technicalDetails||''} onChange={e=>set('technicalDetails',e.target.value)} placeholder="Example: MS angle 50x50x5, IS 2062, 6m length, delivery to Chakan MIDC. Include material certificate / TC needs." /></label>
    <label className="span2">Upload/reference at least 2 images or documents<input className="input" type="file" multiple accept="image/*,.pdf,.dwg,.dxf,.xlsx,.xls,.doc,.docx" onChange={e=>handleFiles(e.target.files)} /><span className="muted">Local MVP stores filenames only. In production this connects to S3/Cloudinary/Drive storage.</span></label>
    {!!form.mediaGallery?.length && <div className="span2 uploadPreviewGrid">{form.mediaGallery.map((item:any, idx:number)=> item.dataUrl ? <div className="uploadPreviewCard" key={idx}><img src={item.dataUrl} alt={item.name || 'upload preview'} /><b>{item.name}</b></div> : <div className="uploadPreviewCard docPreviewCard" key={idx}><div className="docIcon">📄</div><b>{item.name}</b></div>)}</div>}
    <label className="span2">Image / document / drawing links<textarea value={form.mediaLinks||''} onChange={e=>set('mediaLinks',e.target.value)} placeholder="Paste at least 2 links, one per line: Google Drive image, drawing link, certificate link, stock photo link." /></label><div className="span2 quotePreview"><b>Delivery logic preview:</b><span>{deliveryEstimate(form)}</span></div>
    <div className="span2" style={{display:'flex',gap:12,flexWrap:'wrap',alignItems:'center'}}><button className="btn" disabled={saving}>{saving?'Submitting...':'Submit verified requirement'}</button><a className="btn secondary" href="/public-marketplace">View marketplace</a>{message && <span className={message.includes('success') || message.includes('Reference') ? 'success' : 'notice'}>{message}</span>}</div>
  </form>;
}
