"use client";
import {useEffect,useMemo,useState} from 'react';
import {formatINR,starterSuppliers,type ScrapSupplier} from '@/lib/data';
const stages:ScrapSupplier['stage'][]=['New Lead','Verified','Negotiation','Active Supplier','Follow-up'];
const empty={company:'',owner:'',phone:'',city:'Pune',metal:'Steel Scrap',grade:'HMS 1&2',quantity:'',rate:0,stage:'New Lead' as ScrapSupplier['stage'],notes:'',lastContact:'Today'};
export default function ScrapSupplierFunnel(){const[items,setItems]=useState<ScrapSupplier[]>(starterSuppliers);const[form,setForm]=useState(empty);const[search,setSearch]=useState('');
useEffect(()=>{const saved=localStorage.getItem('talmech-scrap-suppliers');if(saved)try{setItems(JSON.parse(saved))}catch{}},[]);useEffect(()=>{localStorage.setItem('talmech-scrap-suppliers',JSON.stringify(items))},[items]);
const filtered=items.filter(i=>`${i.company} ${i.owner} ${i.city} ${i.metal} ${i.stage}`.toLowerCase().includes(search.toLowerCase()));
const totals=useMemo(()=>({suppliers:items.length,active:items.filter(i=>i.stage==='Active Supplier').length,monthly:items.reduce((a,i)=>a+(Number(i.rate)||0),0)}),[items]);
function add(){if(!form.company||!form.phone)return;setItems([{...form,id:crypto.randomUUID(),rate:Number(form.rate)||0},...items]);setForm(empty)}
function update(id:string,stage:ScrapSupplier['stage']){setItems(items.map(i=>i.id===id?{...i,stage,lastContact:'Today'}:i))}
function remove(id:string){setItems(items.filter(i=>i.id!==id))}
function csv(){const rows=[['Company','Owner','Phone','City','Metal','Grade','Quantity','Rate','Stage','Notes'],...items.map(i=>[i.company,i.owner,i.phone,i.city,i.metal,i.grade,i.quantity,String(i.rate),i.stage,i.notes])];const blob=new Blob([rows.map(r=>r.map(x=>`"${String(x).replace(/"/g,'""')}"`).join(',')).join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='talmech-scrap-suppliers.csv';a.click();}
return <><div className="grid kpis"><div className="card"><b>{totals.suppliers}</b><p className="muted">Scrap suppliers</p></div><div className="card"><b>{totals.active}</b><p className="muted">Active suppliers</p></div><div className="card"><b>{formatINR(totals.monthly)}</b><p className="muted">Listed rate value</p></div><div className="card"><button className="btn" onClick={csv}>Export CSV</button></div></div><section className="grid cards3 section"><div className="card" style={{gridColumn:'span 1'}}><h2>Add supplier lead</h2><div className="form"><input className="input" placeholder="Company" value={form.company} onChange={e=>setForm({...form,company:e.target.value})}/><input className="input" placeholder="Owner name" value={form.owner} onChange={e=>setForm({...form,owner:e.target.value})}/><input className="input" placeholder="WhatsApp phone with country code" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><input className="input" placeholder="City" value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/><select value={form.metal} onChange={e=>setForm({...form,metal:e.target.value})}>{['Steel Scrap','Copper Scrap','Aluminum Scrap','Brass Scrap','Mixed Scrap'].map(x=><option key={x}>{x}</option>)}</select><input className="input" placeholder="Grade / quality" value={form.grade} onChange={e=>setForm({...form,grade:e.target.value})}/><input className="input" placeholder="Quantity e.g. 40 MT/month" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/><input className="input" type="number" placeholder="Expected rate per MT" value={form.rate||''} onChange={e=>setForm({...form,rate:Number(e.target.value)})}/><textarea className="input" placeholder="Notes: quality, pickup, GST, photos" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><button className="btn" onClick={add}>Add to Funnel</button></div></div><div className="card" style={{gridColumn:'span 2'}}><div className="row"><h2>Supplier coordination funnel</h2><input className="input smallInput" placeholder="Search suppliers" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="funnel">{stages.map(stage=><div className="lane" key={stage}><h3>{stage}</h3>{filtered.filter(i=>i.stage===stage).map(i=><div className="supplierCard" key={i.id}><b>{i.company}</b><p>{i.owner} • {i.city}</p><p>{i.metal} / {i.grade}</p><p>{i.quantity} • {formatINR(i.rate)}/MT</p><p className="muted">{i.notes}</p><div className="row"><a className="btn secondary" href={`https://wa.me/${i.phone}`} target="_blank">WhatsApp</a><button className="btn secondary" onClick={()=>remove(i.id)}>Delete</button></div><select value={i.stage} onChange={e=>update(i.id,e.target.value as ScrapSupplier['stage'])}>{stages.map(s=><option key={s}>{s}</option>)}</select></div>)}</div>)}</div></div></section></>}
