'use client';
import {useMemo,useState,useEffect} from 'react';
import {formatINR} from '@/lib/data';

type Stage='New'|'Contacted'|'Quoted'|'Negotiation'|'Won'|'Lost';
type LeadType='Manufacturer / Supplier'|'Consumer / Buyer'|'Logistics Partner';
type Lead={id:string;type:LeadType;company:string;contact:string;phone:string;email:string;city:string;state:string;metal:string;qty:string;frequency:string;stage:Stage;nextAction:string;value:number;notes:string};
const stages:Stage[]=['New','Contacted','Quoted','Negotiation','Won','Lost'];
const leadTypes:LeadType[]=['Manufacturer / Supplier','Consumer / Buyer','Logistics Partner'];
const starter:Lead[]=[
{id:'m1',type:'Manufacturer / Supplier',company:'Pune Alloy Works',contact:'Purchase Head',phone:'919876543210',email:'sales@punealloy.example',city:'Pune',state:'Maharashtra',metal:'Steel',qty:'25 MT',frequency:'Weekly',stage:'Contacted',nextAction:'Send intro + request stock list',value:1562500,notes:'Can supply small lots; ask for GST, grade certificate and loading point.'},
{id:'m2',type:'Manufacturer / Supplier',company:'Mumbai Copper House',contact:'Owner',phone:'918765432109',email:'info@mumbaicopper.example',city:'Mumbai',state:'Maharashtra',metal:'Copper',qty:'3 MT',frequency:'Fortnightly',stage:'Negotiation',nextAction:'Negotiate commission and delivery terms',value:2550000,notes:'Good for small/medium copper lots; needs verified buyer before blocking material.'},
{id:'c1',type:'Consumer / Buyer',company:'EV Components Cluster',contact:'Sourcing Manager',phone:'917654321098',email:'buy@evcluster.example',city:'Chakan',state:'Maharashtra',metal:'Copper',qty:'1.5 MT',frequency:'Monthly',stage:'Quoted',nextAction:'Share quote with delivery timeline',value:1275000,notes:'Consumes copper busbar and wire rods; sensitive to delivery reliability.'},
{id:'c2',type:'Consumer / Buyer',company:'Rajkot Casting Unit',contact:'Plant Owner',phone:'916543210987',email:'purchase@rajkotcast.example',city:'Rajkot',state:'Gujarat',metal:'Aluminum',qty:'8 MT',frequency:'Monthly',stage:'New',nextAction:'Cold call and qualify grade',value:1920000,notes:'Potential recurring aluminum consumer.'},
{id:'l1',type:'Logistics Partner',company:'Western Freight Movers',contact:'Dispatcher',phone:'915432109876',email:'ops@westernfreight.example',city:'Pune',state:'Maharashtra',metal:'City-to-city consignments',qty:'1-32 MT',frequency:'Daily',stage:'Contacted',nextAction:'Collect route rate card',value:45000,notes:'Need Pune-Mumbai, Pune-Ahmedabad, Mumbai-Delhi per MT freight rates.'}
];
const topDemand=[
['Copper','Mumbai → Pune','EV, electrical panels, HVAC','Very High','Find 1-3 MT lots; high commission per deal'],
['Steel','Pune → Chakan','Forging, fabrication, auto','High','Target recurring 20-50 MT buyers'],
['Aluminum','Ahmedabad → Rajkot','Casting, extrusion, solar frames','High','Good small-lot demand with lower working capital'],
['Brass','Delhi → Faridabad','Valves, fittings, machining','High','Broker grade-specific lots; verify composition'],
['Copper Scrap','Mumbai → Pune','Recycling, wire drawing','Very High','Scrap arbitrage possible after contamination check'],
['Steel Scrap','Pune → Raipur','Melting, rolling mills','Medium','Logistics margin can decide profitability'],
['Zinc','Raipur → Delhi','Galvanizing','Medium','Track construction order flow'],
['Nickel','Chennai → Pune','Stainless and plating','Medium','Low volume but high-value commission'],
['Lead','Delhi → Jaipur','Battery recyclers','Medium','Require compliance and documentation'],
['Silver','Mumbai → Surat','Industrial and jewellery','Medium','Deal only with verified parties']
];

function mapLeadType(v:any):LeadType{const s=String(v||'').toLowerCase(); if(s.includes('supplier')||s.includes('seller')||s.includes('manufacturer')) return 'Manufacturer / Supplier'; if(s.includes('logistics')) return 'Logistics Partner'; return 'Consumer / Buyer'}
function mapBackendLead(x:any):Lead{return {id:x.id,type:mapLeadType(x.leadType),company:x.company||x.companyName||'Imported lead',contact:x.contact||x.contactName||'',phone:x.phone||'',email:x.email||'',city:x.city||'',state:x.state||'',metal:x.metal||'',qty:x.quantity||x.qty||'',frequency:x.frequency||'To qualify',stage:(x.stage||'New') as Stage,nextAction:x.nextAction||'Call and qualify requirement',value:Number(x.value||0),notes:x.notes||x.technicalDetails||''}}
const templates={
manufacturer:`Subject: Talmech Trading - verified buyers for your metal stock\n\nHello {{name}},\n\nI am from Talmech Trading. We help metal manufacturers, stockists and scrap suppliers connect with verified industrial buyers for small-to-medium quantity consignments across regions.\n\nOur MVP tracks regional demand, buyer requirements, live/reference rates, logistics coordination and documentation so you can move stock faster without spending extra time on follow-ups.\n\nPlease share your available metal, grade, quantity, city, GST status and expected rate. We can bring relevant buyer enquiries and coordinate quote, logistics and invoice flow.\n\nRegards,\nTalmech Trading`,
consumer:`Subject: Talmech Trading - faster sourcing for your metal requirements\n\nHello {{name}},\n\nI am from Talmech Trading. We help manufacturers and industrial consumers source metals and scrap in small-to-medium quantities from verified regional suppliers.\n\nTell us your metal, grade, quantity, delivery city and required timeline. We will compare available suppliers, arrange logistics options and share a clear landed quote so your procurement team saves time.\n\nOur focus is transparent pricing, reliable coordination and repeat supply relationships.\n\nRegards,\nTalmech Trading`,
logistics:`Subject: City-to-city metal consignment logistics partnership\n\nHello {{name}},\n\nTalmech Trading coordinates small-to-medium metal consignments between suppliers and industrial buyers. We are building a verified logistics network for routes such as Pune-Mumbai, Pune-Ahmedabad, Mumbai-Delhi and regional industrial clusters.\n\nPlease share your vehicle types, capacity, route rate card, loading/unloading support, insurance option and payment terms.\n\nRegards,\nTalmech Trading`
};
function safePhone(p:string){return p.replace(/[^0-9]/g,'')}
export default function TradingCRM(){
const [leads,setLeads]=useState<Lead[]>(starter);const [type,setType]=useState<LeadType>('Consumer / Buyer');const [selected,setSelected]=useState('consumer');const [query,setQuery]=useState('');
useEffect(()=>{async function load(){let local:Lead[]=starter;const saved=localStorage.getItem('talmech_trading_crm');if(saved)try{local=JSON.parse(saved)}catch{};try{const d=await fetch('/api/crm-leads',{cache:'no-store'}).then(r=>r.json());const backend=(d.leads||[]).map(mapBackendLead);const localOnly=local.filter((l:any)=>!backend.some((b:any)=>b.id===l.id));setLeads([...backend,...localOnly]);}catch{setLeads(local)}}load()},[]);
useEffect(()=>{localStorage.setItem('talmech_trading_crm',JSON.stringify(leads))},[leads]);
const filtered=useMemo(()=>leads.filter(l=>[l.company,l.city,l.state,l.metal,l.type,l.stage].join(' ').toLowerCase().includes(query.toLowerCase())),[leads,query]);
const pipeline=useMemo(()=>filtered.reduce((s,l)=>s+l.value,0),[filtered]);
async function addLead(formData:FormData){const v=Object.fromEntries(formData.entries());const lead:Lead={id:crypto.randomUUID(),type:v.type as LeadType,company:String(v.company||''),contact:String(v.contact||''),phone:String(v.phone||''),email:String(v.email||''),city:String(v.city||''),state:String(v.state||''),metal:String(v.metal||''),qty:String(v.qty||''),frequency:String(v.frequency||''),stage:'New',nextAction:String(v.nextAction||'Call and qualify requirement'),value:Number(v.value||0),notes:String(v.notes||'')};try{const r=await fetch('/api/crm-leads',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({leadType:lead.type,stage:lead.stage,company:lead.company,contact:lead.contact,phone:lead.phone,email:lead.email,city:lead.city,state:lead.state,metal:lead.metal,quantity:lead.qty,frequency:lead.frequency,value:lead.value,nextAction:lead.nextAction,notes:lead.notes})}).then(x=>x.json());if(r.ok)setLeads([mapBackendLead(r.lead),...leads]);else setLeads([lead,...leads])}catch{setLeads([lead,...leads])}}
function updateStage(id:string,stage:Stage){setLeads(leads.map(l=>l.id===id?{...l,stage}:l))}
function removeLead(id:string){setLeads(leads.filter(l=>l.id!==id))}
function exportCsv(){const header=Object.keys(leads[0]||{}).join(',');const rows=leads.map(l=>Object.values(l).map(v=>`"${String(v).replaceAll('"','""')}"`).join(','));const blob=new Blob([[header,...rows].join('\n')],{type:'text/csv'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='talmech-crm-funnels.csv';a.click();URL.revokeObjectURL(url)}
const template=selected==='manufacturer'?templates.manufacturer:selected==='logistics'?templates.logistics:templates.consumer;
return <main className="container section"><span className="eyebrow">Mediator CRM + demand intelligence</span><h1 className="pageTitle">Trading CRM for demand, supply and logistics commission</h1><p className="lead">Build separate funnels for suppliers/manufacturers, consumers/buyers and transport partners. Track small-to-medium regional requirements, send cold emails, follow up by phone/WhatsApp, coordinate logistics and earn brokerage or commission.</p>
<div className="grid cards4"><div className="card"><b>{filtered.length}</b><p className="muted">Active records</p></div><div className="card"><b>{formatINR(pipeline)}</b><p className="muted">Visible pipeline</p></div><div className="card"><b>{filtered.filter(l=>l.type==='Consumer / Buyer').length}</b><p className="muted">Buyer/consumer leads</p></div><div className="card"><b>{filtered.filter(l=>l.type==='Manufacturer / Supplier').length}</b><p className="muted">Supplier leads</p></div></div>
<section className="section grid cards2"><div className="panel"><div className="row"><div><h2>Add new funnel lead</h2><p className="muted">Use this after cold call, email, WhatsApp, IndiaMART enquiry or supplier reference.</p></div><button onClick={exportCsv} className="btn secondary">Export CSV</button></div><form onSubmit={(e)=>{e.preventDefault();addLead(new FormData(e.currentTarget));e.currentTarget.reset();setType('Consumer / Buyer')}} className="form crmForm"><label>Lead type<select name="type" value={type} onChange={e=>setType(e.target.value as LeadType)}>{leadTypes.map(t=><option key={t}>{t}</option>)}</select></label><label>Company<input className="input" name="company" required placeholder="Company / supplier name"/></label><label>Contact person<input className="input" name="contact" placeholder="Owner / purchase manager"/></label><label>Phone<input className="input" name="phone" placeholder="91XXXXXXXXXX"/></label><label>Email<input className="input" name="email" placeholder="name@company.com"/></label><label>City<input className="input" name="city" placeholder="Pune"/></label><label>State<input className="input" name="state" placeholder="Maharashtra"/></label><label>Metal / service<input className="input" name="metal" placeholder={type==='Logistics Partner'?'Pune to Mumbai 16 MT truck':'Copper / Steel / Aluminum / Scrap'}/></label><label>Quantity<input className="input" name="qty" placeholder="3 MT / 25 MT / 1 truck"/></label><label>Frequency<input className="input" name="frequency" placeholder="One-time / weekly / monthly"/></label><label>Estimated value<input className="input" type="number" name="value" placeholder="1200000"/></label><label>Next action<input className="input" name="nextAction" placeholder="Send intro, collect grade/rate, arrange quote"/></label><label className="span2">Notes<textarea className="input" name="notes" placeholder="Grade, GST, delivery city, payment terms, pain points"/></label><button className="btn span2">Add to CRM</button></form></div>
<div className="panel"><h2>Default cold outreach intro</h2><p className="muted">Copy this for email/WhatsApp. Replace placeholders before sending.</p><div className="filters"><button className={selected==='manufacturer'?'btn':'btn secondary'} onClick={()=>setSelected('manufacturer')}>Manufacturer/Supplier</button><button className={selected==='consumer'?'btn':'btn secondary'} onClick={()=>setSelected('consumer')}>Consumer/Buyer</button><button className={selected==='logistics'?'btn':'btn secondary'} onClick={()=>setSelected('logistics')}>Logistics</button></div><textarea className="input templateBox" value={template} readOnly/><div className="row"><button className="btn" onClick={()=>navigator.clipboard.writeText(template)}>Copy intro</button><a className="btn secondary" href={`mailto:?subject=${encodeURIComponent('Talmech Trading - regional metal trading support')}&body=${encodeURIComponent(template)}`}>Open email</a></div><div className="card noShadow"><b>Cold-call script</b><p className="muted">“Hello, I am calling from Talmech Trading. We connect verified regional metal suppliers and industrial consumers for small-to-medium consignments. May I know which metal grades you supply or consume monthly, your city, quantity range and current buying/selling challenge?”</p></div></div></section>
<section className="section"><div className="row"><div><h2>AI market watch - daily top 10 demand opportunities</h2><p className="muted">MVP scoring model based on price movement, city demand, CRM enquiries, transaction notes and news/API inputs once connected.</p></div><input className="input smallInput" placeholder="Search city / metal / stage" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="tableWrap"><table><thead><tr><th>Rank</th><th>Metal</th><th>Region</th><th>Demand driver</th><th>Signal</th><th>Recommended action</th></tr></thead><tbody>{topDemand.map((r,i)=><tr key={r[0]+r[1]}><td>#{i+1}</td><td>{r[0]}</td><td>{r[1]}</td><td>{r[2]}</td><td>{r[3]}</td><td>{r[4]}</td></tr>)}</tbody></table></div></section>
<section className="section"><h2>Pipeline board</h2><div className="funnel crmFunnel">{stages.map(s=><div className="lane" key={s}><h3>{s} <span className="muted">({filtered.filter(l=>l.stage===s).length})</span></h3>{filtered.filter(l=>l.stage===s).map(l=><div className="supplierCard" key={l.id}><div className="row"><b>{l.company}</b><span className="badge">{l.type.split(' ')[0]}</span></div><p>{l.metal} • {l.qty} • {l.frequency}</p><p className="muted">{l.city}, {l.state}</p><p><b>{formatINR(l.value)}</b></p><p className="muted">Next: {l.nextAction}</p><p className="muted">{l.notes}</p><select value={l.stage} onChange={e=>updateStage(l.id,e.target.value as Stage)}>{stages.map(st=><option key={st}>{st}</option>)}</select><div className="row" style={{marginTop:10}}><a className="btn secondary" href={`https://wa.me/${safePhone(l.phone)}?text=${encodeURIComponent(template)}`} target="_blank">WhatsApp</a><a className="btn secondary" href={`tel:+${safePhone(l.phone)}`}>Call</a><button className="btn secondary" onClick={()=>removeLead(l.id)}>Delete</button></div></div>)}</div>)}</div></section>
<section className="section grid cards3"><div className="card"><h3>Commission logic</h3><p className="muted">Start with buyer/seller commission or spread. For small/medium lots, also quote logistics coordination fee and documentation fee separately.</p></div><div className="card"><h3>Verification checklist</h3><p className="muted">GST, company address, material photos, grade certificate, weighbridge slip, payment terms, loading point and delivery liability.</p></div><div className="card"><h3>Daily AI inputs to connect later</h3><p className="muted">Live price APIs, Google News/RSS, your CRM activity, quote history, booked orders, supplier availability and city-wise logistics rates.</p></div></section></main>}
