export type Metal={slug:string;name:string;symbol:string;price:number;unit:string;change:number;city:string;state:string;grade:string;stock:string;demand:string;forecast:string;apps:string[];history:number[];source?:string;updatedAt?:string;liveCapable?:boolean};
export const metals:Metal[]=[
{slug:'steel',name:'Steel',symbol:'Fe/C',price:62500,unit:'MT',change:1.8,city:'Pune',state:'Maharashtra',grade:'IS 2062 / EN8',stock:'4,200 MT',demand:'High',forecast:'Infrastructure and automotive demand should keep regional prices firm.',apps:['Construction','Automotive','Forging','Infrastructure'],history:[58,59,60,61,62,62.5],source:'Manual regional quote / supplier input',liveCapable:false},
{slug:'copper',name:'Copper',symbol:'Cu',price:850000,unit:'MT',change:2.4,city:'Mumbai',state:'Maharashtra',grade:'ETP / OFC',stock:'640 MT',demand:'Very High',forecast:'EV, grid and electronics demand can support upside momentum.',apps:['Electrical wiring','EV motors','HVAC','Renewable energy'],history:[790,805,812,832,844,850],source:'Metals.dev / MetalpriceAPI when configured',liveCapable:true},
{slug:'aluminum',name:'Aluminum',symbol:'Al',price:240000,unit:'MT',change:-.7,city:'Ahmedabad',state:'Gujarat',grade:'6061 / 6082',stock:'1,900 MT',demand:'Medium',forecast:'Solar frames, packaging and transport demand remain supportive.',apps:['Extrusion','Solar frames','Packaging','Aerospace'],history:[236,238,241,242,240,240],source:'Metals.dev when configured',liveCapable:true},
{slug:'brass',name:'Brass',symbol:'CuZn',price:510000,unit:'MT',change:1.2,city:'Delhi',state:'Delhi',grade:'CZ121 / IS 319',stock:'780 MT',demand:'High',forecast:'Fittings, valves and electrical component demand is stable.',apps:['Valves','Fittings','Terminals','Machining'],history:[487,492,498,505,508,510],source:'Calculated manual quote from copper + zinc premium',liveCapable:false},
{slug:'zinc',name:'Zinc',symbol:'Zn',price:265000,unit:'MT',change:.9,city:'Raipur',state:'Chhattisgarh',grade:'SHG 99.995%',stock:'980 MT',demand:'Medium',forecast:'Galvanizing demand should remain stable with construction activity.',apps:['Galvanizing','Die casting','Alloys','Chemicals'],history:[251,254,256,262,263,265],source:'Metals.dev when configured',liveCapable:true},
{slug:'nickel',name:'Nickel',symbol:'Ni',price:1580000,unit:'MT',change:3.1,city:'Chennai',state:'Tamil Nadu',grade:'Class 1',stock:'220 MT',demand:'High',forecast:'Battery and stainless steel demand can keep premium grades active.',apps:['Stainless steel','Batteries','Superalloys','Plating'],history:[1430,1460,1495,1535,1560,1580],source:'Metals.dev when configured',liveCapable:true},
{slug:'lead',name:'Lead',symbol:'Pb',price:185000,unit:'MT',change:.4,city:'Delhi',state:'Delhi',grade:'99.97%',stock:'380 MT',demand:'Medium',forecast:'Battery recycling and cable shielding demand remain stable.',apps:['Batteries','Cable sheathing','Radiation shielding','Alloys'],history:[174,176,179,181,184,185],source:'Metals.dev when configured',liveCapable:true},
{slug:'iron',name:'Iron',symbol:'Fe',price:48000,unit:'MT',change:.7,city:'Raipur',state:'Chhattisgarh',grade:'Pig Iron / Sponge Iron',stock:'1,500 MT',demand:'High',forecast:'Foundry and induction furnace demand can create regional arbitrage opportunities.',apps:['Foundries','Casting','Rolling mills','Machinery'],history:[43,44,45,46,47,48],source:'Manual regional quote / supplier input',liveCapable:false},
{slug:'gold',name:'Gold',symbol:'Au',price:7200000,unit:'KG',change:.6,city:'Mumbai',state:'Maharashtra',grade:'24K / 999',stock:'Dealer quote',demand:'High',forecast:'Safe-haven demand can support firm pricing.',apps:['Jewellery','Investment','Electronics'],history:[6900,6980,7040,7110,7180,7200],source:'Metals.dev / MetalpriceAPI when configured',liveCapable:true},
{slug:'silver',name:'Silver',symbol:'Ag',price:92000,unit:'KG',change:1.4,city:'Mumbai',state:'Maharashtra',grade:'999',stock:'Dealer quote',demand:'High',forecast:'Solar and electronics demand can improve industrial pull.',apps:['Solar panels','Jewellery','Electronics'],history:[86,87,88,90,91,92],source:'Metals.dev / MetalpriceAPI when configured',liveCapable:true}
];
export const scrap=[['Steel Scrap','HMS 1&2','Pune','120 MT',42000,'Clean industrial scrap'],['Copper Scrap','Millberry / Berry','Mumbai','18 MT',612000,'High purity, low contamination'],['Aluminum Scrap','6063 Extrusion','Ahmedabad','44 MT',178000,'Sorted and bundled'],['Brass Scrap','Honey Brass','Delhi','22 MT',385000,'Mixed fittings and turnings'],['Mixed Scrap','Factory mixed','Raipur','75 MT',35000,'Requires sorting']];
export type ScrapSupplier={id:string;company:string;owner:string;phone:string;city:string;metal:string;grade:string;quantity:string;rate:number;stage:'New Lead'|'Verified'|'Negotiation'|'Active Supplier'|'Follow-up';notes:string;lastContact:string};
export const starterSuppliers:ScrapSupplier[]=[
{id:'sup-1',company:'Shree Scrap Solutions',owner:'Amit Patil',phone:'919876543210',city:'Pune',metal:'Steel Scrap',grade:'HMS 1&2',quantity:'80 MT/month',rate:42000,stage:'Active Supplier',notes:'Clean factory scrap. Needs pickup coordination every Friday.',lastContact:'Today'},
{id:'sup-2',company:'Metro Copper Recyclers',owner:'Sana Shaikh',phone:'918765432109',city:'Mumbai',metal:'Copper Scrap',grade:'Millberry',quantity:'12 MT/month',rate:612000,stage:'Negotiation',notes:'Ask for GST invoice and contamination photos before confirming.',lastContact:'Yesterday'},
{id:'sup-3',company:'Gujarat Alloy Recovery',owner:'Harsh Mehta',phone:'917654321098',city:'Ahmedabad',metal:'Aluminum Scrap',grade:'6063 extrusion',quantity:'35 MT/month',rate:178000,stage:'Verified',notes:'Good extrusion stock. Needs transport quotation.',lastContact:'2 days ago'}
];
export const buyers=['Tata Manufacturing Cluster','ABC Auto Components','Prime Steel Works','EV Power Systems','Western Forging Hub','Metro Infra Projects','Shakti Electricals','Bharat HVAC Systems','Unity Fabricators','Global Export Buyer'];
export const sellers=['Global Metals Pvt Ltd','RawCore Industries','Shree Scrap Solutions','Metro Alloy Traders','Prime Copper House','Vishal Steel Depot','Noble Aluminum','Hind Alloy Supply','Sai Metal Recycling','Eastern Zinc Traders'];
export const leads=[['ABC Industries','Hot',1200000,'Copper','Tomorrow','WhatsApp'],['Prime Steel Works','Warm',800000,'Steel','Friday','Email'],['EV Power Systems','Hot',2400000,'Copper','Today','Call'],['Dubai Metal Trader','Export',4000000,'Aluminum','Monday','Email']];
export const formatINR=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
export const calcQuote=(price:number,qty:number)=>{const base=price*qty,logistics=qty>50?45000:12000,platform=base*.008,gst=(base+logistics+platform)*.18;return{base,logistics,platform,gst,total:base+logistics+platform+gst}};
export const getMetal=(slug:string)=>metals.find(m=>m.slug===slug);
