export type VehicleType={id:string;name:string;capacityMt:number;lengthFt:number;widthFt:number;heightFt:number;baseRatePerKm:number;loadingBuffer:number;notes:string};
export type LogisticsInput={pickup:string;drop:string;metal:string;product:string;weightMt:number;lengthFt:number;widthFt:number;heightFt:number;urgent:boolean;loadingType:string};
export type LogisticsQuote={vehicle:VehicleType;distanceKm:number;base:number;fuelSurcharge:number;tollEstimate:number;loadingUnloading:number;insurance:number;gst:number;total:number;ratePerMt:number;transitTime:string;confidence:'High'|'Medium'|'Low';reason:string;updatedAt:string;routeUrl:string;providerSearches:{label:string;url:string}[]};

export const vehicles:VehicleType[]=[
{id:'pickup',name:'Pickup / Tata Ace',capacityMt:1.2,lengthFt:7,widthFt:4.8,heightFt:5,baseRatePerKm:26,loadingBuffer:900,notes:'Samples, small bars, urgent small consignments'},
{id:'407',name:'Tata 407 / LCV',capacityMt:3,lengthFt:10,widthFt:6,heightFt:7,baseRatePerKm:38,loadingBuffer:1500,notes:'Small lots, fabricated parts, pipes, sheets'},
{id:'eicher14',name:'14 ft Eicher',capacityMt:5,lengthFt:14,widthFt:7,heightFt:7,baseRatePerKm:48,loadingBuffer:2200,notes:'Regular city-to-city metal lots'},
{id:'eicher17',name:'17 ft Eicher',capacityMt:7,lengthFt:17,widthFt:7.2,heightFt:7.2,baseRatePerKm:58,loadingBuffer:2800,notes:'Bars, channels, coils, mixed products'},
{id:'truck19',name:'19 ft Truck',capacityMt:9,lengthFt:19,widthFt:7.5,heightFt:7.5,baseRatePerKm:68,loadingBuffer:3500,notes:'Heavy metal loads and long route lots'},
{id:'truck22',name:'22 ft Truck',capacityMt:12,lengthFt:22,widthFt:7.5,heightFt:7.5,baseRatePerKm:82,loadingBuffer:4200,notes:'Large buyer/supplier consignments'},
{id:'openbody',name:'Open Body Truck',capacityMt:16,lengthFt:24,widthFt:8,heightFt:8,baseRatePerKm:98,loadingBuffer:5000,notes:'Angles, channels, pipes, scrap bundles, machinery steel'},
{id:'trailer32',name:'32 ft Trailer',capacityMt:22,lengthFt:32,widthFt:8,heightFt:8.5,baseRatePerKm:125,loadingBuffer:7000,notes:'Long bars, channels, coils, bulk industrial movement'},
{id:'trailer40',name:'40 ft Trailer / Container',capacityMt:28,lengthFt:40,widthFt:8,heightFt:8.5,baseRatePerKm:155,loadingBuffer:9000,notes:'Full truckload, export/import linked movement'}
];

export const productVehicleRules:Record<string,string[]>={
'TMT Bars':['truck19','truck22','trailer32'],
'MS Angles':['openbody','trailer32','truck22'],
'MS Channels':['openbody','trailer32','truck22'],
'MS Beams / Joists':['trailer32','trailer40','openbody'],
'MS Rounds / Bright Bars':['eicher17','truck19','trailer32'],
'HR / CR Sheets':['eicher17','truck19','truck22'],
'HR / CR Coils':['truck22','trailer32','trailer40'],
'Pipes / Hollow Sections':['openbody','trailer32','trailer40'],
'Copper Wire / Rod':['407','eicher14','eicher17','truck19'],
'Aluminum Extrusion':['407','eicher14','eicher17','truck19'],
'Brass Components':['pickup','407','eicher14'],
'Scrap Bundles':['openbody','truck22','trailer32'],
'Mixed Metal Scrap':['openbody','truck19','truck22'],
'Finished Components':['pickup','407','eicher14','eicher17']
};

export const cityCoordinates:Record<string,{lat:number;lng:number}>={
'Pune':{lat:18.5204,lng:73.8567},'Chakan':{lat:18.7606,lng:73.8637},'Pimpri-Chinchwad':{lat:18.6298,lng:73.7997},'Mumbai':{lat:19.076,lng:72.8777},'Navi Mumbai':{lat:19.033,lng:73.0297},'Thane':{lat:19.2183,lng:72.9781},'Nashik':{lat:19.9975,lng:73.7898},'Nagpur':{lat:21.1458,lng:79.0882},'Kolhapur':{lat:16.705,lng:74.2433},'Aurangabad':{lat:19.8762,lng:75.3433},'Solapur':{lat:17.6599,lng:75.9064},
'Ahmedabad':{lat:23.0225,lng:72.5714},'Surat':{lat:21.1702,lng:72.8311},'Vadodara':{lat:22.3072,lng:73.1812},'Rajkot':{lat:22.3039,lng:70.8022},'Jamnagar':{lat:22.4707,lng:70.0577},'Ankleshwar':{lat:21.6264,lng:73.0152},'Vapi':{lat:20.3893,lng:72.9106},'Gandhidham':{lat:23.0753,lng:70.1337},'Morbi':{lat:22.8173,lng:70.8377},
'Delhi':{lat:28.7041,lng:77.1025},'New Delhi':{lat:28.6139,lng:77.209},'Okhla':{lat:28.5355,lng:77.2839},'Mayapuri':{lat:28.6284,lng:77.1231},'Noida':{lat:28.5355,lng:77.391},'Ghaziabad':{lat:28.6692,lng:77.4538},'Faridabad':{lat:28.4089,lng:77.3178},'Gurugram':{lat:28.4595,lng:77.0266},'Sonipat':{lat:28.9288,lng:77.0913},'Panipat':{lat:29.3909,lng:76.9635},
'Raipur':{lat:21.2514,lng:81.6296},'Bhilai':{lat:21.1938,lng:81.3509},'Durg':{lat:21.1904,lng:81.2849},'Bilaspur':{lat:22.0797,lng:82.1391},'Raigarh':{lat:21.8974,lng:83.395},'Korba':{lat:22.3595,lng:82.7501},
'Chennai':{lat:13.0827,lng:80.2707},'Coimbatore':{lat:11.0168,lng:76.9558},'Hosur':{lat:12.7409,lng:77.8253},'Salem':{lat:11.6643,lng:78.146},'Madurai':{lat:9.9252,lng:78.1198},
'Bengaluru':{lat:12.9716,lng:77.5946},'Mysuru':{lat:12.2958,lng:76.6394},'Belagavi':{lat:15.8497,lng:74.4977},'Hubballi':{lat:15.3647,lng:75.124},'Ballari':{lat:15.1394,lng:76.9214},
'Hyderabad':{lat:17.385,lng:78.4867},'Sangareddy':{lat:17.6248,lng:78.0867},'Warangal':{lat:17.9689,lng:79.5941},
'Indore':{lat:22.7196,lng:75.8577},'Pithampur':{lat:22.6133,lng:75.6826},'Bhopal':{lat:23.2599,lng:77.4126},'Dewas':{lat:22.9676,lng:76.0534},'Jabalpur':{lat:23.1815,lng:79.9864},'Gwalior':{lat:26.2183,lng:78.1828},
'Jaipur':{lat:26.9124,lng:75.7873},'Bhiwadi':{lat:28.2088,lng:76.8446},'Alwar':{lat:27.553,lng:76.6346},'Jodhpur':{lat:26.2389,lng:73.0243},'Udaipur':{lat:24.5854,lng:73.7125},'Kota':{lat:25.2138,lng:75.8648},
'Ludhiana':{lat:30.901,lng:75.8573},'Mandi Gobindgarh':{lat:30.6632,lng:76.3001},'Jalandhar':{lat:31.326,lng:75.5762},'Amritsar':{lat:31.634,lng:74.8723},
'Kolkata':{lat:22.5726,lng:88.3639},'Howrah':{lat:22.5958,lng:88.2636},'Durgapur':{lat:23.5204,lng:87.3119},'Asansol':{lat:23.6739,lng:86.9524},'Haldia':{lat:22.0667,lng:88.0698},
'Jamshedpur':{lat:22.8046,lng:86.2029},'Ranchi':{lat:23.3441,lng:85.3096},'Bokaro':{lat:23.6693,lng:86.1511},'Dhanbad':{lat:23.7957,lng:86.4304},'Adityapur':{lat:22.7835,lng:86.1571},
'Rourkela':{lat:22.2604,lng:84.8536},'Jharsuguda':{lat:21.8554,lng:84.0062},'Bhubaneswar':{lat:20.2961,lng:85.8245},'Cuttack':{lat:20.4625,lng:85.883},'Angul':{lat:20.8444,lng:85.1511},'Kalinganagar':{lat:20.9684,lng:86.0468},
'Haridwar':{lat:29.9457,lng:78.1642},'Rudrapur':{lat:28.9875,lng:79.4141},'Roorkee':{lat:29.8543,lng:77.888},'Dehradun':{lat:30.3165,lng:78.0322},
'Kochi':{lat:9.9312,lng:76.2673},'Visakhapatnam':{lat:17.6868,lng:83.2185},'Vijayawada':{lat:16.5062,lng:80.648},'Goa':{lat:15.2993,lng:74.124},'Panaji':{lat:15.4909,lng:73.8278}
};

export function extractCity(input:string){const clean=input.split(',')[0].trim();return cityCoordinates[clean]?clean:Object.keys(cityCoordinates).find(c=>input.toLowerCase().includes(c.toLowerCase()))||clean}
export function haversineKm(a:{lat:number;lng:number},b:{lat:number;lng:number}){const R=6371;const dLat=(b.lat-a.lat)*Math.PI/180;const dLon=(b.lng-a.lng)*Math.PI/180;const lat1=a.lat*Math.PI/180;const lat2=b.lat*Math.PI/180;const h=Math.sin(dLat/2)**2+Math.sin(dLon/2)**2*Math.cos(lat1)*Math.cos(lat2);return Math.round(2*R*Math.asin(Math.sqrt(h))*1.22)}
export function pickVehicles(product:string,weightMt:number,lengthFt:number){const preferred=productVehicleRules[product]||vehicles.map(v=>v.id);return vehicles.filter(v=>preferred.includes(v.id)&&v.capacityMt>=weightMt&&v.lengthFt>=lengthFt).concat(vehicles.filter(v=>v.capacityMt>=weightMt&&v.lengthFt>=lengthFt&&!preferred.includes(v.id))).slice(0,4)}
export function calculateQuotes(input:LogisticsInput):LogisticsQuote[]{const pickupCity=extractCity(input.pickup);const dropCity=extractCity(input.drop);const a=cityCoordinates[pickupCity];const b=cityCoordinates[dropCity];const estimatedDistance=a&&b?haversineKm(a,b):Math.max(80,Math.round(input.pickup.length*input.drop.length*1.7));const selected=pickVehicles(input.product,input.weightMt,input.lengthFt);const updatedAt=new Date().toISOString();const urgency=input.urgent?1.18:1;return selected.map(v=>{const distanceKm=estimatedDistance;const base=Math.round(Math.max(2500,distanceKm*v.baseRatePerKm*urgency));const fuelSurcharge=Math.round(base*0.14);const tollEstimate=Math.round(Math.max(350,distanceKm*2.4));const loadingUnloading=Math.round(v.loadingBuffer+(input.weightMt*350));const insurance=Math.round(Math.max(300,input.weightMt*180));const subtotal=base+fuelSurcharge+tollEstimate+loadingUnloading+insurance;const gst=Math.round(subtotal*0.18);const total=subtotal+gst;const days=Math.max(1,Math.ceil(distanceKm/450));const routeUrl=`https://www.google.com/maps/dir/${encodeURIComponent(input.pickup)}/${encodeURIComponent(input.drop)}`;const q1=`${v.name} transport ${input.pickup} to ${input.drop}`;const q2=`metal logistics transporter ${pickupCity} ${dropCity}`;return{vehicle:v,distanceKm,base,fuelSurcharge,tollEstimate,loadingUnloading,insurance,gst,total,ratePerMt:Math.round(total/input.weightMt),transitTime:`${days}-${days+1} day${days>1?'s':''}`,confidence:a&&b?'Medium':'Low',reason:a&&b?'Distance estimated from built-in Indian industrial city coordinates. Final carrier quote may vary by route, diesel, toll, loading point and return load.':'City coordinate not found; using fallback estimate. Verify with transporter.',updatedAt,routeUrl,providerSearches:[{label:'Google transporters',url:`https://www.google.com/search?q=${encodeURIComponent(q1)}`},{label:'Google Maps transporters',url:`https://www.google.com/maps/search/${encodeURIComponent(q2)}`},{label:'IndiaMART transporters',url:`https://www.google.com/search?q=${encodeURIComponent(`site:indiamart.com transporter ${pickupCity} ${dropCity}`)}`},{label:'Justdial logistics',url:`https://www.google.com/search?q=${encodeURIComponent(`site:justdial.com logistics transporter ${pickupCity}`)}`}]} as LogisticsQuote})}

export type LogisticsPaymentResponsibility='BUYER'|'SELLER'|'SPLIT';
export type LogisticsProviderStatus='ACTIVE'|'PENDING_CONTRACT'|'SUSPENDED'|'INACTIVE';
export type LogisticsProviderRecord={id:string;createdAt:string;updatedAt?:string;status:LogisticsProviderStatus;companyName:string;contactName?:string;phone?:string;email?:string;website?:string;gstNumber?:string;panNumber?:string;address?:string;country:string;state:string;city:string;nearbyCities:string[];serviceableCountries:string[];serviceableStates:string[];serviceableCities:string[];serviceTypes:string[];specializations:string[];deliveryType:string;speed:string;capacityMt:number;fleetSize?:number;availabilityDates:string[];unavailableDates:string[];baseRate:number;ratePerKm:number;ratePerMt:number;minimumCharge:number;loadingCharge:number;insurancePercent:number;fuelSurchargePercent:number;gstPercent:number;contractStatus:'NOT_SENT'|'SENT'|'SIGNED'|'EXPIRED';contractNotes?:string;paymentResponsibilityDefault:LogisticsPaymentResponsibility;adminNotes?:string;adminPricingLocked:boolean};
export type LogisticsMatchInput={pickup:string;drop:string;pickupCity?:string;dropCity?:string;state?:string;country?:string;weightMt:number;product?:string;serviceType?:string;date?:string;paymentResponsibility?:LogisticsPaymentResponsibility;pickupLat?:number|string;pickupLng?:number|string;dropLat?:number|string;dropLng?:number|string};
export const defaultLogisticsProviders:LogisticsProviderRecord[]=[
{id:'LGP-PUNE-001',createdAt:'2026-05-01T09:00:00.000Z',status:'ACTIVE',companyName:'Western Industrial Logistics',contactName:'Operations Desk',phone:'919876543210',email:'ops@westernindustrial.example',website:'',gstNumber:'27ABCDE1234F1Z5',address:'Chakan MIDC, Pune',country:'India',state:'Maharashtra',city:'Pune',nearbyCities:['Chakan','Pimpri-Chinchwad','Mumbai','Nashik','Kolhapur'],serviceableCountries:['India'],serviceableStates:['Maharashtra','Gujarat','Madhya Pradesh','Karnataka'],serviceableCities:['Pune','Chakan','Pimpri-Chinchwad','Mumbai','Navi Mumbai','Thane','Nashik','Kolhapur','Ahmedabad','Surat','Indore','Bengaluru'],serviceTypes:['FTL','Part Load','Same Day Industrial'],specializations:['Steel','Forging Components','Auto Components','Bars','Sheets'],deliveryType:'Road transport',speed:'Standard / priority',capacityMt:22,fleetSize:18,availabilityDates:[],unavailableDates:[],baseRate:3200,ratePerKm:62,ratePerMt:850,minimumCharge:6500,loadingCharge:1800,insurancePercent:.003,fuelSurchargePercent:.08,gstPercent:.18,contractStatus:'SENT',contractNotes:'Contract and SLA to be finalized before production use.',paymentResponsibilityDefault:'BUYER',adminNotes:'Seed provider for Maharashtra industrial routes.',adminPricingLocked:true},
{id:'LGP-MUM-002',createdAt:'2026-05-01T09:05:00.000Z',status:'ACTIVE',companyName:'Coastal Freight Movers',contactName:'Dispatch Coordinator',phone:'918765432109',email:'dispatch@coastalfreight.example',gstNumber:'27XYZDE9876K1Z2',address:'Navi Mumbai logistics hub',country:'India',state:'Maharashtra',city:'Navi Mumbai',nearbyCities:['Mumbai','Thane','Pune','Vapi','Surat'],serviceableCountries:['India'],serviceableStates:['Maharashtra','Gujarat','Rajasthan'],serviceableCities:['Mumbai','Navi Mumbai','Thane','Pune','Vapi','Surat','Vadodara','Ahmedabad','Rajkot','Jaipur'],serviceTypes:['FTL','Container','Export Port Movement'],specializations:['Coils','Pipes','Non-ferrous Metals','Container Loads'],deliveryType:'Road / port-linked',speed:'Standard',capacityMt:28,fleetSize:12,availabilityDates:[],unavailableDates:[],baseRate:4500,ratePerKm:78,ratePerMt:900,minimumCharge:8500,loadingCharge:2500,insurancePercent:.004,fuelSurchargePercent:.1,gstPercent:.18,contractStatus:'NOT_SENT',contractNotes:'Onboarding pending.',paymentResponsibilityDefault:'BUYER',adminPricingLocked:true},
{id:'LGP-DEL-003',createdAt:'2026-05-01T09:10:00.000Z',status:'PENDING_CONTRACT',companyName:'Northline Metal Carriers',contactName:'Vendor Desk',phone:'917654321098',email:'vendor@northline.example',gstNumber:'07LMNOP2222A1Z7',address:'Mayapuri Industrial Area, Delhi',country:'India',state:'Delhi',city:'Delhi',nearbyCities:['Mayapuri','Okhla','Noida','Ghaziabad','Faridabad','Gurugram','Panipat'],serviceableCountries:['India'],serviceableStates:['Delhi','Haryana','Uttar Pradesh','Punjab','Rajasthan'],serviceableCities:['Delhi','New Delhi','Mayapuri','Okhla','Noida','Ghaziabad','Faridabad','Gurugram','Sonipat','Panipat','Ludhiana','Mandi Gobindgarh','Jaipur','Bhiwadi'],serviceTypes:['FTL','Part Load','Scrap Movement'],specializations:['Scrap','Steel','Machinery','Industrial Raw Material'],deliveryType:'Road transport',speed:'Standard',capacityMt:16,fleetSize:10,availabilityDates:[],unavailableDates:[],baseRate:3600,ratePerKm:66,ratePerMt:780,minimumCharge:7000,loadingCharge:2200,insurancePercent:.0035,fuelSurchargePercent:.09,gstPercent:.18,contractStatus:'SENT',contractNotes:'Activate only after contract signature.',paymentResponsibilityDefault:'BUYER',adminPricingLocked:true}
];
export function normaliseCity(value:string){return extractCity(value||'').trim()}
export function providerOperatesIn(provider:LogisticsProviderRecord,city:string,state?:string,country='India'){const c=normaliseCity(city).toLowerCase();const cities=[provider.city,...provider.nearbyCities,...provider.serviceableCities].map(x=>String(x).toLowerCase());const states=provider.serviceableStates.map(x=>String(x).toLowerCase());return provider.serviceableCountries.map(x=>x.toLowerCase()).includes(country.toLowerCase())&&(!state||states.includes(state.toLowerCase())||provider.state.toLowerCase()===state.toLowerCase())&&cities.includes(c)}
export function estimateLogisticsProviderCost(provider:LogisticsProviderRecord,input:LogisticsMatchInput){const pc=normaliseCity(input.pickupCity||input.pickup),dc=normaliseCity(input.dropCity||input.drop);const distanceKm=routeDistanceKm(input.pickup||pc,input.drop||dc,input.pickupLat,input.pickupLng,input.dropLat,input.dropLng);const pickupPoint=reliableCoord(input.pickupLat,input.pickupLng);const pickupDistanceKm=cityCoordinates[provider.city]&&(pickupPoint||cityCoordinates[pc])?haversineKm(cityCoordinates[provider.city],pickupPoint||cityCoordinates[pc]):0;const base=Math.max(provider.minimumCharge,provider.baseRate);const distance=Math.round(distanceKm*provider.ratePerKm);const weight=Math.round(Number(input.weightMt||1)*provider.ratePerMt);const loading=Math.round(provider.loadingCharge);const sub=base+distance+weight+loading;const insurance=Math.round(sub*provider.insurancePercent);const fuel=Math.round((base+distance)*provider.fuelSurchargePercent);const beforeGst=sub+insurance+fuel;const gst=Math.round(beforeGst*provider.gstPercent);const total=Math.round(beforeGst+gst);const resp=input.paymentResponsibility||provider.paymentResponsibilityDefault||'BUYER';const buyerPayable=resp==='SELLER'?0:resp==='SPLIT'?Math.round(total/2):total;const sellerPayable=resp==='SELLER'?total:resp==='SPLIT'?total-buyerPayable:0;return{distanceKm,pickupDistanceKm,cost:{base:Math.round(base),distance,weight,loading,insurance,fuel,gst,total,buyerPayable,sellerPayable}}}
export function matchLogisticsProviders(input:LogisticsMatchInput,providers:LogisticsProviderRecord[]){const pc=normaliseCity(input.pickupCity||input.pickup),dc=normaliseCity(input.dropCity||input.drop),date=input.date||new Date().toISOString().slice(0,10),service=String(input.serviceType||'').toLowerCase();return providers.filter(p=>p.status==='ACTIVE'||p.status==='PENDING_CONTRACT').map(p=>{const pickupOk=providerOperatesIn(p,pc,input.state,input.country||'India'),dropOk=providerOperatesIn(p,dc,undefined,input.country||'India'),serviceOk=!service||[...p.serviceTypes,...p.specializations].some(s=>s.toLowerCase().includes(service)),dateOk=!p.unavailableDates.includes(date)&&(p.availabilityDates.length===0||p.availabilityDates.includes(date)),capacityOk=p.capacityMt>=Number(input.weightMt||0);const calc=estimateLogisticsProviderCost(p,input);const score=(pickupOk?50:0)+(dropOk?25:0)+(serviceOk?10:0)+(dateOk?10:0)+(capacityOk?10:0)-Math.min(20,calc.pickupDistanceKm/20)-Math.min(20,calc.cost.total/50000);return{provider:p,...calc,score:Math.round(score*100)/100,available:Boolean(pickupOk&&dropOk&&serviceOk&&dateOk&&capacityOk),reason:`${pickupOk?'Pickup city covered':'Pickup city not covered'} • ${dropOk?'delivery city covered':'delivery city not covered'} • ${dateOk?'available':'date unavailable'} • ${capacityOk?'capacity ok':'capacity too low'}`}}).sort((a,b)=>Number(b.available)-Number(a.available)||b.score-a.score||a.cost.total-b.cost.total)}
export function selectDefaultLogisticsProvider(input:LogisticsMatchInput,providers:LogisticsProviderRecord[]){return matchLogisticsProviders(input,providers).find(x=>x.available)||null}

export type SmartDispatchEta={ready:boolean;distanceKm:number;travelMinutes:number;bufferMinutes:number;totalMinutes:number;label:string;byText:string;iso:string;reason:string};
export function coordFrom(lat:any,lng:any){const la=Number(lat),ln=Number(lng);return Number.isFinite(la)&&Number.isFinite(ln)&&Math.abs(la)<=90&&Math.abs(ln)<=180?{lat:la,lng:ln}:null}
export function isIndiaCoord(point:any){return Boolean(point&&point.lat>=6&&point.lat<=38&&point.lng>=68&&point.lng<=98)}
export function reliableCoord(lat:any,lng:any){const p=coordFrom(lat,lng);return isIndiaCoord(p)?p:null}
export function routeDistanceKm(pickup:string,drop:string,pickupLat?:any,pickupLng?:any,dropLat?:any,dropLng?:any){const directA=reliableCoord(pickupLat,pickupLng),directB=reliableCoord(dropLat,dropLng);if(directA&&directB)return Math.max(1,haversineKm(directA,directB));const pc=normaliseCity(pickup),dc=normaliseCity(drop);const a=cityCoordinates[pc],b=cityCoordinates[dc];if(a&&b)return pc===dc?8:haversineKm(a,b);return Math.max(25,Math.round((String(pickup).length+String(drop).length)*2.2));}
export function formatDuration(totalMinutes:number){const minutes=Math.max(0,Math.round(totalMinutes));const days=Math.floor(minutes/1440);const hrs=Math.floor((minutes%1440)/60);const mins=minutes%60;if(days>0)return `${days} day${days>1?'s':''}${hrs?` ${hrs} hrs`:''}`;if(hrs>0)return `${hrs} hrs${mins?` ${mins} min`:''}`;return `${mins} min`;}
export function formatDeliveryBy(date:Date){return date.toLocaleString('en-IN',{weekday:'short',hour:'numeric',minute:'2-digit',hour12:true,day:'2-digit',month:'short'});}
export function calculateSmartDispatchEta(args:{pickup:string;drop:string;dispatchReadiness?:string;productionLeadTime?:string;deliveryEta?:string;readyDispatchTime?:string;orderDate?:Date;speedKmH?:number;bufferMinutes?:number;pickupLat?:any;pickupLng?:any;dropLat?:any;dropLng?:any;routeDistanceKmOverride?:any;routeDurationMinutesOverride?:any}){const ready=String(args.dispatchReadiness||'').toUpperCase()==='READY_STOCK';const overrideDistance=Number(args.routeDistanceKmOverride||0);const overrideDuration=Number(args.routeDurationMinutesOverride||0);const distanceKm=overrideDistance>0?Math.round(overrideDistance*10)/10:routeDistanceKm(args.pickup,args.drop,args.pickupLat,args.pickupLng,args.dropLat,args.dropLng);if(!ready){const fallback=args.deliveryEta||args.readyDispatchTime||args.productionLeadTime||'3 + 1 days after supplier confirmation';return{ready:false,distanceKm,travelMinutes:0,bufferMinutes:0,totalMinutes:0,label:fallback,byText:'After preparation and dispatch confirmation',iso:'',reason:'Supplier needs preparation/procurement time; normal day-based ETA is shown.'} as SmartDispatchEta;}const speed=args.speedKmH||42;const bufferMinutes=args.bufferMinutes??360;const travelMinutes=overrideDuration>0?Math.max(15,Math.ceil(overrideDuration)):Math.max(30,Math.ceil((distanceKm/speed)*60));const totalMinutes=travelMinutes+bufferMinutes;const start=args.orderDate||new Date();const by=new Date(start.getTime()+totalMinutes*60000);const precision=overrideDistance>0?'OpenRouteService road route':(reliableCoord(args.pickupLat,args.pickupLng)&&reliableCoord(args.dropLat,args.dropLng)?'pin-to-pin estimate':'city-to-city estimate');return{ready:true,distanceKm,travelMinutes,bufferMinutes,totalMinutes,label:`Delivery in ${formatDuration(totalMinutes)}`,byText:`Get your product by ${formatDeliveryBy(by)}`,iso:by.toISOString(),reason:`Ready stock: ${distanceKm} km ${precision} + ${formatDuration(bufferMinutes)} pickup/loading/admin buffer + ${formatDuration(travelMinutes)} road transit.`} as SmartDispatchEta;}
export function toWeightMt(quantity:any,unit:any){const q=Number(String(quantity||'').replace(/,/g,'').match(/\d+(?:\.\d+)?/)?.[0]||0);const u=String(unit||'MT').toUpperCase();if(!q)return 0;if(u==='KG')return q/1000;if(u==='TON'||u==='TONNE'||u==='MT')return q;return Math.max(0.1,q/1000)}
export type VehicleFreightOption={id:string;providerId?:string;providerName:string;vehicleId:string;vehicleName:string;capacityMt:number;distanceKm:number;pickupDistanceKm:number;ratePerKm:number;base:number;distance:number;loading:number;weight:number;insurance:number;fuel:number;gst:number;total:number;buyerPayable:number;sellerPayable:number;eta:SmartDispatchEta;adminPricingLocked:boolean;recommended:boolean;reason:string};
export function estimateProviderVehicleCost(provider:LogisticsProviderRecord,input:LogisticsMatchInput & {vehicleId?:string;dispatchReadiness?:string;routeDistanceKmOverride?:any;routeDurationMinutesOverride?:any}){const pc=normaliseCity(input.pickupCity||input.pickup),dc=normaliseCity(input.dropCity||input.drop);const overrideDistance=Number((input as any).routeDistanceKmOverride||0);const distanceKm=overrideDistance>0?Math.round(overrideDistance*10)/10:routeDistanceKm(input.pickup||pc,input.drop||dc,input.pickupLat,input.pickupLng,input.dropLat,input.dropLng);const pickupPoint=reliableCoord(input.pickupLat,input.pickupLng);const pickupDistanceKm=cityCoordinates[provider.city]&&(pickupPoint||cityCoordinates[pc])?haversineKm(cityCoordinates[provider.city],pickupPoint||cityCoordinates[pc]):0;const allowed=pickVehicles(input.product||'TMT Bars',Number(input.weightMt||1),1);const vehicle=(input.vehicleId?vehicles.find(v=>v.id===input.vehicleId):null)||allowed[0]||vehicles[0];const ratePerKm=Math.max(Number(provider.ratePerKm||0),Number(vehicle.baseRatePerKm||0));const base=Math.round(Number(provider.baseRate||0));const distance=Math.round(distanceKm*ratePerKm);const loading=Math.round(Number(provider.loadingCharge||0)+vehicle.loadingBuffer);const weight=Math.round(Number(input.weightMt||1)*Number(provider.ratePerMt||0));const fuel=Math.round(distance*Number(provider.fuelSurchargePercent||0));const beforeInsurance=base+distance+loading+weight+fuel;const insurance=Math.round(beforeInsurance*Number(provider.insurancePercent||0));const beforeMinimum=beforeInsurance+insurance;const beforeGst=Math.max(Number(provider.minimumCharge||0),beforeMinimum);const gst=Math.round(beforeGst*Number(provider.gstPercent||0.18));const total=Math.round(beforeGst+gst);const resp=input.paymentResponsibility||provider.paymentResponsibilityDefault||'BUYER';const buyerPayable=resp==='SELLER'?0:resp==='SPLIT'?Math.round(total/2):total;const sellerPayable=resp==='SELLER'?total:resp==='SPLIT'?total-buyerPayable:0;const eta=calculateSmartDispatchEta({pickup:input.pickup||pc,drop:input.drop||dc,dispatchReadiness:input.dispatchReadiness,pickupLat:input.pickupLat,pickupLng:input.pickupLng,dropLat:input.dropLat,dropLng:input.dropLng,routeDistanceKmOverride:(input as any).routeDistanceKmOverride,routeDurationMinutesOverride:(input as any).routeDurationMinutesOverride});return{id:`${provider.id}-${vehicle.id}`,providerId:provider.id,providerName:provider.companyName,vehicleId:vehicle.id,vehicleName:vehicle.name,capacityMt:vehicle.capacityMt,distanceKm,pickupDistanceKm,ratePerKm,base:Math.round(base),distance,loading,weight,insurance,fuel,gst,total,buyerPayable,sellerPayable,eta,adminPricingLocked:provider.adminPricingLocked!==false,recommended:false,reason:`${vehicle.name} selected by weight/capacity. Admin locked rate/km ₹${ratePerKm}. ${eta.reason}`} as VehicleFreightOption;}
export function buildVehicleFreightOptions(input:LogisticsMatchInput & {dispatchReadiness?:string;vehicleId?:string;routeDistanceKmOverride?:any;routeDurationMinutesOverride?:any},providers:LogisticsProviderRecord[]){const matched=matchLogisticsProviders(input,providers).filter(m=>m.available).slice(0,4);const preferred=pickVehicles(input.product||'TMT Bars',Number(input.weightMt||1),1).slice(0,4);let rows:VehicleFreightOption[]=[];for(const m of matched){for(const v of preferred){rows.push(estimateProviderVehicleCost(m.provider,{...input,vehicleId:v.id}))}}if(rows.length===0){const dummy=defaultLogisticsProviders[0];rows=preferred.map(v=>estimateProviderVehicleCost(dummy,{...input,vehicleId:v.id}))}rows=rows.sort((a,b)=>a.total-b.total||a.pickupDistanceKm-b.pickupDistanceKm).slice(0,6);return rows.map((r,i)=>({...r,recommended:i===0}));}
