export type ProductCategory = {
  metal: string;
  slug: string;
  products: string[];
  grades: string[];
  buyerIndustries: string[];
  supplierTypes: string[];
  qualityChecks: string[];
  seoKeywords: string[];
};

export const commissionPolicy = [
  {type:'Small brokerage deal', range:'₹10,000 - ₹1,00,000', commission:'2.0% - 3.0%', note:'Useful for first-time regional deals where Talmech coordinates buyer, supplier and logistics.'},
  {type:'Repeat buyer/supplier deal', range:'₹1,00,000 - ₹10,00,000', commission:'1.0% - 2.0%', note:'Reduce fee for verified repeat accounts and faster payment cycles.'},
  {type:'Large bulk order', range:'Above ₹10,00,000', commission:'0.5% - 1.0%', note:'Keep thin but safe margin; charge extra for logistics coordination if required.'},
  {type:'Logistics coordination', range:'Any shipment', commission:'₹500 - ₹5,000 or 3% freight markup', note:'Charge as service fee only after transporter quote is confirmed.'}
];

export const productCategories: ProductCategory[] = [
  {metal:'Steel',slug:'steel',products:['TMT bars','MS angles','MS channels','MS beams','MS flats','MS rounds','MS square bars','HR sheets','HR coils','CR sheets','GP/GC sheets','MS plates','Chequered plates','MS pipes','GI pipes','Hollow sections','Square tubes','Rectangular tubes','Wire rods','Binding wire','Fasteners','Fabricated structures','Forged shafts','HMS scrap','CRC bundle scrap','Turning scrap'],grades:['Fe 500D','Fe 550D','IS 2062 E250/E350','EN8','EN9','EN24','SAE 1018','SS 304','SS 316','GI 275 GSM','HMS 1&2'],buyerIndustries:['Construction contractors','fabricators','PEB manufacturers','automobile component makers','forging units','machining shops','infrastructure contractors','agriculture equipment manufacturers','warehouses and racking companies'],supplierTypes:['rolling mills','steel stockists','service centers','coil processors','fabricators with surplus stock','scrap yards'],qualityChecks:['test certificate','heat number','weight bridge slip','chemical composition','surface rust check','straightness','length tolerance','GST invoice'],seoKeywords:['steel suppliers near me','TMT bars price','MS angle dealer','steel stockist India','steel fabrication material']},
  {metal:'Copper',slug:'copper',products:['Copper cathode','Copper rod','Copper wire','Copper strip','Copper sheet','Copper busbar','Copper pipe','Copper winding wire','Copper scrap Berry','Copper scrap Millberry','Copper armature scrap'],grades:['C101','C110','ETP','OFC','99.9% cathode','Millberry 99.9%'],buyerIndustries:['electrical panel makers','transformer manufacturers','cable manufacturers','motor rewinders','HVAC contractors','electronics units','renewable energy contractors'],supplierTypes:['copper importers','non-ferrous dealers','wire rod suppliers','scrap aggregators'],qualityChecks:['purity certificate','conductivity','insulation condition','oil contamination','foreign material','weighment'],seoKeywords:['copper supplier India','copper scrap buyer','copper wire manufacturer','copper busbar supplier']},
  {metal:'Aluminum',slug:'aluminum',products:['Aluminum ingot','Aluminum billet','Aluminum extrusion','Aluminum sheet','Aluminum coil','Aluminum profile','Aluminum pipe','Aluminum section','6063 scrap','UBC scrap','cast aluminum scrap'],grades:['6061','6063','6082','7075','1100','8011','LM6','ADC12'],buyerIndustries:['solar structure makers','window and façade fabricators','automobile component makers','packaging units','electrical enclosure makers','aerospace component shops'],supplierTypes:['extrusion plants','aluminum stockists','ingot suppliers','recyclers','importers'],qualityChecks:['temper','surface finish','hardness','section drawing','bundle weight','alloy certificate'],seoKeywords:['aluminum extrusion supplier','aluminium sheet dealer','6063 aluminum profile','aluminum scrap rate']},
  {metal:'Brass',slug:'brass',products:['Brass rods','Brass sheets','Brass tubes','Brass fittings','Brass valves','Brass inserts','Brass components','Honey brass scrap','Brass turning scrap'],grades:['CZ121','IS 319','C360','C260','Free cutting brass','Naval brass'],buyerIndustries:['sanitary fittings','electrical components','hardware manufacturers','precision turned parts','valve makers','instrument fittings'],supplierTypes:['Jamnagar brass manufacturers','non-ferrous stockists','turning scrap dealers','component manufacturers'],qualityChecks:['lead content','zinc percentage','surface finish','thread quality','dimension tolerance','mixed metal contamination'],seoKeywords:['brass manufacturer Jamnagar','brass rod supplier','brass components India','brass scrap dealer']},
  {metal:'Iron',slug:'iron',products:['Pig iron','Cast iron scrap','Sponge iron','Iron ore fines','Foundry returns','CI castings','SG iron castings'],grades:['Foundry grade','Basic grade','SG iron','Grey iron','FeM 80+'],buyerIndustries:['foundries','casting units','machine base makers','pump manufacturers','agriculture equipment makers'],supplierTypes:['sponge iron plants','foundries','iron traders','casting scrap dealers'],qualityChecks:['carbon/silicon content','phosphorus/sulphur','moisture','size fraction','slag contamination'],seoKeywords:['pig iron supplier','foundry raw material','cast iron scrap buyer']},
  {metal:'Zinc',slug:'zinc',products:['Zinc ingot','Zinc alloy','Zinc die casting scrap','Galvanizing zinc','Zamak'],grades:['SHG 99.995%','Zamak 3','Zamak 5','Galvanizing grade'],buyerIndustries:['galvanizing plants','die casting units','hardware makers','automotive small parts'],supplierTypes:['zinc ingot dealers','non-ferrous traders','die casting recyclers'],qualityChecks:['purity','dross level','ingot brand','moisture','mixed alloy check'],seoKeywords:['zinc ingot supplier','zamak supplier','galvanizing zinc dealer']},
  {metal:'Nickel',slug:'nickel',products:['Nickel cathode','Nickel plate','Nickel alloy scrap','Stainless steel nickel scrap','Inconel scrap'],grades:['Class 1','Ni 99.8%','Inconel 600','Inconel 625','Monel'],buyerIndustries:['stainless steel plants','alloy manufacturers','aerospace component makers','chemical process equipment'],supplierTypes:['nickel importers','alloy scrap dealers','special metal stockists'],qualityChecks:['Ni percentage','alloy mix','radioactivity check','certificate','surface contamination'],seoKeywords:['nickel supplier India','nickel alloy scrap','inconel scrap buyer']},
  {metal:'Lead',slug:'lead',products:['Lead ingot','Lead sheet','Battery scrap','Lead oxide','Lead alloy'],grades:['99.97%','Remelted lead','Battery grade','Antimonial lead'],buyerIndustries:['battery manufacturers','radiation shielding','cable sheathing','chemical units'],supplierTypes:['battery recyclers','lead smelters','non-ferrous traders'],qualityChecks:['purity','acid leakage','battery scrap compliance','moisture','weight'],seoKeywords:['lead ingot supplier','battery scrap dealer','lead recycler']},
  {metal:'Forging Components',slug:'forging-components',products:['Forged shafts','forged rings','flanges','gear blanks','connecting rods','crankshafts','forged bars','machined forgings','closed die forgings'],grades:['EN8','EN9','EN19','EN24','16MnCr5','20MnCr5','42CrMo4','SS 304','SS 316'],buyerIndustries:['automobile OEM vendors','tractor parts','railway parts','oil and gas','valve industry','aerospace machining','heavy engineering'],supplierTypes:['forging units','machining shops','heat treatment vendors','raw material stockists'],qualityChecks:['forging drawing','heat treatment certificate','UT/MPI reports','dimension report','material TC','hardness'],seoKeywords:['forging manufacturers India','forged shaft supplier','EN24 forging','machined forging vendor']},
  {metal:'Aerospace & Precision Components',slug:'aerospace-precision-components',products:['CNC machined parts','turned components','aerospace brackets','precision pins','bushes','fasteners','jigs fixtures','tooling parts'],grades:['Al 7075','Al 6061','SS 17-4PH','Titanium Grade 5','Inconel','EN24','D2','H13'],buyerIndustries:['aerospace suppliers','defence vendors','automation OEMs','medical device manufacturers','tool rooms'],supplierTypes:['CNC shops','VMC/HMC vendors','aerospace approved vendors','tool rooms'],qualityChecks:['drawing revision','CMM report','material cert','NDT report','surface treatment','traceability'],seoKeywords:['precision components supplier','aerospace machining India','CNC component manufacturer']}
];

export const marketplaceDemoListings = [
  {type:'SELL',title:'TMT Fe 500D ready stock',metal:'Steel',product:'TMT bars',grade:'Fe 500D',qty:'5 MT',location:'Pune, Maharashtra',pincode:'411026',price:'Supplier quote',dispatch:'1-2 days',verified:true},
  {type:'BUY',title:'Need copper scrap Millberry',metal:'Copper',product:'Copper scrap',grade:'Millberry 99.9%',qty:'500 KG',location:'Mumbai, Maharashtra',pincode:'400072',price:'Best landed quote',dispatch:'Urgent',verified:false},
  {type:'SELL',title:'Aluminum extrusion profiles',metal:'Aluminum',product:'Extrusion profiles',grade:'6063 T6',qty:'2 MT',location:'Ahmedabad, Gujarat',pincode:'382415',price:'Live quote',dispatch:'3 days',verified:true},
  {type:'BUY',title:'Forged shaft EN24 required',metal:'Forging Components',product:'Forged shaft',grade:'EN24',qty:'100 Nos',location:'Rajkot, Gujarat',pincode:'360004',price:'Quote required',dispatch:'Drawing based',verified:false},
  {type:'SELL',title:'Honey brass scrap available',metal:'Brass',product:'Brass scrap',grade:'Honey brass',qty:'800 KG',location:'Jamnagar, Gujarat',pincode:'361004',price:'Market linked',dispatch:'Ready',verified:true},
  {type:'BUY',title:'MS channels and angles for fabrication',metal:'Steel',product:'MS channels / angles',grade:'IS 2062',qty:'3 MT',location:'Chakan MIDC, Maharashtra',pincode:'410501',price:'Need delivered rate',dispatch:'This week',verified:false}
];
