export type LiveStatus='api-live'|'supplier-quote'|'formula-estimate'|'manual-market';
export type MetalProduct={metalSlug:string;metal:string;category:string;product:string;commonGrades:string[];forms:string[];primaryUses:string[];buyerIndustries:string[];qualityChecks:string[];searchTerms:string[];priceStatus:LiveStatus;pricingNote:string;unit:'MT'|'KG'|'piece'|'meter'};

export const metalProducts:MetalProduct[]=[
{metalSlug:'steel',metal:'Steel',category:'Structural steel',product:'MS Angles',commonGrades:['IS 2062 E250','E350'],forms:['L angle','equal angle','unequal angle'],primaryUses:['fabrication','frames','support structures','towers'],buyerIndustries:['fabricators','construction contractors','solar structure makers','warehouse builders'],qualityChecks:['size and thickness','straightness','mill test certificate','rust and pitting','weight bridge slip'],searchTerms:['MS angle suppliers','steel angle fabricators','structural steel fabricators'],priceStatus:'supplier-quote',pricingNote:'Needs regional supplier quote. Public APIs do not give city-wise live angle price.',unit:'MT'},
{metalSlug:'steel',metal:'Steel',category:'Structural steel',product:'MS Channels',commonGrades:['ISMC','IS 2062 E250'],forms:['C channel','ISMC channel'],primaryUses:['fabrication','machine base','building structure','trailers'],buyerIndustries:['fabricators','equipment manufacturers','construction contractors'],qualityChecks:['section size','web/flange thickness','straightness','MTC','surface condition'],searchTerms:['MS channel buyer','steel channel fabricators','ISMC channel suppliers'],priceStatus:'supplier-quote',pricingNote:'Track by supplier quote city-wise.',unit:'MT'},
{metalSlug:'steel',metal:'Steel',category:'Long products',product:'TMT Bars',commonGrades:['Fe 500','Fe 500D','Fe 550','Fe 600'],forms:['8mm to 40mm bars'],primaryUses:['RCC construction','infrastructure','real estate'],buyerIndustries:['builders','contractors','infrastructure companies','dealers'],qualityChecks:['brand/mill','diameter','bend test','rib pattern','IS mark','weight per bundle'],searchTerms:['TMT bar dealers','construction steel buyers','TMT distributors'],priceStatus:'supplier-quote',pricingNote:'Usually regional dealer/mill quote; not reliable from global metal API.',unit:'MT'},
{metalSlug:'steel',metal:'Steel',category:'Long products',product:'MS Rounds / Bright Bars',commonGrades:['EN8','EN9','EN24','C45','IS 2062'],forms:['round bar','bright bar','forged bar'],primaryUses:['shafts','machining','fasteners','tools'],buyerIndustries:['machine shops','auto component makers','forging units','CNC manufacturers'],qualityChecks:['grade chemistry','diameter tolerance','hardness','surface finish','length'],searchTerms:['EN8 round bar buyers','bright bar manufacturers','CNC machining companies'],priceStatus:'supplier-quote',pricingNote:'Grade and size dependent; use supplier quotes.',unit:'MT'},
{metalSlug:'steel',metal:'Steel',category:'Flat products',product:'HR Sheets / HR Coils',commonGrades:['IS 2062','E250','E350'],forms:['hot rolled sheet','coil','plate'],primaryUses:['fabrication','pressing','structures','tanks'],buyerIndustries:['sheet metal fabricators','tank manufacturers','auto ancillary','equipment manufacturers'],qualityChecks:['thickness','coil width','surface scale','flatness','MTC'],searchTerms:['HR sheet buyers','hot rolled coil users','sheet metal fabricators'],priceStatus:'supplier-quote',pricingNote:'Best tracked via mill/dealer quote and regional premium.',unit:'MT'},
{metalSlug:'steel',metal:'Steel',category:'Flat products',product:'CR Sheets / GP / GC Sheets',commonGrades:['CRCA','GP','GC','GI'],forms:['cold rolled sheet','galvanized sheet','corrugated sheet'],primaryUses:['appliances','ducting','panels','roofing'],buyerIndustries:['HVAC duct manufacturers','appliance makers','panel fabricators','roofing contractors'],qualityChecks:['coating gsm','surface finish','thickness tolerance','coil ID','packing condition'],searchTerms:['CR sheet buyers','GI sheet fabricators','HVAC duct manufacturers'],priceStatus:'supplier-quote',pricingNote:'Coating and thickness decide landed price.',unit:'MT'},
{metalSlug:'steel',metal:'Steel',category:'Pipes and tubes',product:'MS Pipes / GI Pipes / Hollow Sections',commonGrades:['ERW','GI','SHS','RHS'],forms:['round pipe','square tube','rectangular tube'],primaryUses:['fabrication','water lines','structures','railings'],buyerIndustries:['pipe fabricators','fencing contractors','greenhouse makers','industrial contractors'],qualityChecks:['OD/ID','wall thickness','coating','weld seam','hydro test if required'],searchTerms:['MS pipe buyers','hollow section fabricators','GI pipe dealers'],priceStatus:'supplier-quote',pricingNote:'Requires city-wise dealer or mill quote.',unit:'MT'},
{metalSlug:'steel',metal:'Steel',category:'Stainless steel',product:'SS Sheets / Pipes / Rods',commonGrades:['SS 304','SS 316','SS 202','SS 410'],forms:['sheet','pipe','rod','coil','flange'],primaryUses:['food equipment','chemical plants','pharma','kitchen equipment'],buyerIndustries:['SS fabricators','pharma equipment makers','food processing equipment','chemical equipment makers'],qualityChecks:['grade test PMI','surface finish','thickness','certificate','magnet check only not enough'],searchTerms:['SS 304 fabricators','stainless steel equipment manufacturers','SS sheet buyers'],priceStatus:'formula-estimate',pricingNote:'Can estimate from nickel/chrome input, but final price needs supplier quote.',unit:'MT'},
{metalSlug:'steel',metal:'Steel',category:'Scrap',product:'HMS Scrap / CRC Bundle / Turning',commonGrades:['HMS 1&2','CRC bundle','boring','turning'],forms:['loose scrap','bundle','turning'],primaryUses:['melting','foundry','re-rolling'],buyerIndustries:['induction furnaces','rolling mills','foundries','scrap processors'],qualityChecks:['contamination','rust','oil','size','moisture','weighbridge','GST invoice'],searchTerms:['HMS scrap buyers','CRC bundle scrap buyers','induction furnace scrap buyers'],priceStatus:'manual-market',pricingNote:'Local scrap is quote-driven. Use your supplier funnel and daily calls.',unit:'MT'},
{metalSlug:'copper',metal:'Copper',category:'Electrical copper',product:'Copper Rod / Wire Rod',commonGrades:['ETP','OFC','99.9%'],forms:['8mm rod','wire rod','coil'],primaryUses:['wire drawing','cables','electrical conductors'],buyerIndustries:['wire manufacturers','cable companies','transformer makers'],qualityChecks:['purity','conductivity','oxygen level','surface cracks','certificate'],searchTerms:['copper wire rod buyers','cable manufacturers','wire drawing companies'],priceStatus:'api-live',pricingNote:'Base copper can be API-live; city premium must be added from supplier quotes.',unit:'MT'},
{metalSlug:'copper',metal:'Copper',category:'Copper products',product:'Copper Busbar / Strip / Sheet',commonGrades:['ETP','DHP','OFC'],forms:['busbar','strip','sheet','foil'],primaryUses:['panels','switchgear','earthing','transformers'],buyerIndustries:['panel builders','switchgear makers','transformer manufacturers','electrical contractors'],qualityChecks:['conductivity','dimension tolerance','edge condition','surface finish','MTC'],searchTerms:['copper busbar buyers','switchgear manufacturers','transformer copper suppliers'],priceStatus:'api-live',pricingNote:'Use live copper base plus fabrication premium.',unit:'MT'},
{metalSlug:'copper',metal:'Copper',category:'Copper scrap',product:'Millberry / Berry / Birch Cliff',commonGrades:['Millberry','Berry','Birch Cliff','Dream'],forms:['wire scrap','cable scrap','mixed copper scrap'],primaryUses:['recycling','melting','refining'],buyerIndustries:['copper recyclers','wire rod mills','scrap processors'],qualityChecks:['insulation percentage','moisture','iron contamination','burnt wire risk','purity'],searchTerms:['copper scrap buyers','millberry scrap buyers','copper recyclers'],priceStatus:'manual-market',pricingNote:'Scrap value follows copper base but deductions are supplier/buyer specific.',unit:'MT'},
{metalSlug:'aluminum',metal:'Aluminum',category:'Extrusion',product:'Aluminum Extrusions / Sections',commonGrades:['6063','6061','6082'],forms:['section','profile','channel','angle'],primaryUses:['windows','solar frames','machine frames','structures'],buyerIndustries:['extrusion users','solar structure makers','facade companies','machine builders'],qualityChecks:['temper','surface finish','anodizing','dimension','bundle weight'],searchTerms:['aluminum extrusion buyers','solar aluminum frame manufacturers','aluminum section users'],priceStatus:'api-live',pricingNote:'Base aluminum can be API-live; extrusion premium is supplier quote.',unit:'MT'},
{metalSlug:'aluminum',metal:'Aluminum',category:'Flat aluminum',product:'Aluminum Sheet / Coil / Plate',commonGrades:['1050','1100','3003','5052','6061'],forms:['sheet','coil','plate'],primaryUses:['cladding','transport','panels','fabrication'],buyerIndustries:['facade companies','bus body builders','panel makers','fabricators'],qualityChecks:['alloy','temper','thickness','flatness','surface scratches'],searchTerms:['aluminum sheet buyers','aluminum coil users','panel fabricators'],priceStatus:'api-live',pricingNote:'Use API base plus conversion premium.',unit:'MT'},
{metalSlug:'aluminum',metal:'Aluminum',category:'Aluminum scrap',product:'Tense / Twitch / Extrusion Scrap / UBC',commonGrades:['Tense','Twitch','6063 extrusion scrap','UBC'],forms:['casting scrap','extrusion scrap','used beverage cans'],primaryUses:['secondary ingot','recycling','casting'],buyerIndustries:['secondary aluminum ingot makers','die casting units','recyclers'],qualityChecks:['iron content','paint/coating','plastic/rubber','moisture','sorted grade'],searchTerms:['aluminum scrap buyers','6063 extrusion scrap buyers','secondary aluminum ingot manufacturers'],priceStatus:'manual-market',pricingNote:'Scrap is regional and quality-driven.',unit:'MT'},
{metalSlug:'brass',metal:'Brass',category:'Brass products',product:'Brass Rod / Bar / Sheet',commonGrades:['CZ121','IS 319','Free cutting brass','Naval brass'],forms:['rod','bar','sheet','coil'],primaryUses:['machining','fittings','valves','decorative hardware'],buyerIndustries:['brass component makers','valve manufacturers','hardware exporters','machining units'],qualityChecks:['copper-zinc ratio','lead content','diameter tolerance','surface','certificate'],searchTerms:['brass rod buyers','brass component manufacturers','brass valve manufacturers'],priceStatus:'formula-estimate',pricingNote:'Estimated from copper+zinc base plus conversion premium.',unit:'MT'},
{metalSlug:'brass',metal:'Brass',category:'Brass scrap',product:'Honey Brass / Ocean Brass / Turnings',commonGrades:['Honey','Ocean','Brass turning'],forms:['fittings scrap','turning','mixed brass'],primaryUses:['remelting','ingot making'],buyerIndustries:['brass ingot makers','Jamnagar brass units','scrap processors'],qualityChecks:['iron/steel mixing','zinc loss','oil in turnings','plastic/rubber','moisture'],searchTerms:['brass scrap buyers','honey brass buyers','Jamnagar brass scrap'],priceStatus:'manual-market',pricingNote:'Most brass scrap is broker/supplier quote driven.',unit:'MT'},
{metalSlug:'zinc',metal:'Zinc',category:'Zinc metal',product:'Zinc Ingot / SHG',commonGrades:['SHG 99.995%','HG'],forms:['ingot','jumbo ingot'],primaryUses:['galvanizing','die casting','alloys'],buyerIndustries:['galvanizing plants','zamak die casting units','brass manufacturers'],qualityChecks:['purity','brand','ingot weight','certificate'],searchTerms:['zinc ingot buyers','galvanizing plants','zamak die casting manufacturers'],priceStatus:'api-live',pricingNote:'API base price plus local premium.',unit:'MT'},
{metalSlug:'zinc',metal:'Zinc',category:'Zinc scrap',product:'Zinc Dross / Ash / Die Casting Scrap',commonGrades:['zinc dross','zinc ash','zamak scrap'],forms:['dross','ash','casting scrap'],primaryUses:['recovery','secondary zinc'],buyerIndustries:['zinc recyclers','galvanizers','secondary metal processors'],qualityChecks:['zinc recovery percentage','ash content','moisture','iron contamination'],searchTerms:['zinc dross buyers','zinc ash buyers','zamak scrap buyers'],priceStatus:'manual-market',pricingNote:'Recovery percentage decides price.',unit:'MT'},
{metalSlug:'nickel',metal:'Nickel',category:'Nickel products',product:'Nickel Cathode / Nickel Alloy / SS Scrap',commonGrades:['Class 1 nickel','Inconel','Monel','SS 304/316 scrap'],forms:['cathode','plate','bar','scrap'],primaryUses:['stainless steel','superalloys','plating','battery materials'],buyerIndustries:['stainless steel mills','alloy makers','plating units','battery material companies'],qualityChecks:['nickel percentage','alloy grade','PMI test','certificate','contamination'],searchTerms:['nickel cathode buyers','Inconel scrap buyers','SS 316 scrap buyers'],priceStatus:'api-live',pricingNote:'Nickel base is API-live; alloy/scrap uses deductions.',unit:'MT'},
{metalSlug:'lead',metal:'Lead',category:'Lead products',product:'Lead Ingot / Battery Scrap / Lead Sheet',commonGrades:['99.97%','remelted lead','battery scrap'],forms:['ingot','sheet','battery scrap'],primaryUses:['batteries','radiation shielding','cable sheathing'],buyerIndustries:['battery manufacturers','battery recyclers','radiation shielding companies','cable manufacturers'],qualityChecks:['purity','legal compliance for battery scrap','moisture/acid','plastic content','certificate'],searchTerms:['lead ingot buyers','battery recyclers','lead sheet manufacturers'],priceStatus:'api-live',pricingNote:'Lead base can be API-live; battery scrap requires compliance quote.',unit:'MT'},
{metalSlug:'iron',metal:'Iron',category:'Foundry inputs',product:'Pig Iron / Sponge Iron / Cast Iron Scrap',commonGrades:['Foundry grade pig iron','Sponge iron DRI','Cast iron scrap'],forms:['ingot','lumps','scrap'],primaryUses:['foundry casting','steelmaking','melting'],buyerIndustries:['foundries','induction furnaces','rolling mills','casting manufacturers'],qualityChecks:['carbon','silicon','sulphur','phosphorus','FeM for DRI','scrap contamination'],searchTerms:['pig iron buyers','sponge iron buyers','cast iron scrap buyers','foundries'],priceStatus:'supplier-quote',pricingNote:'Mostly regional quote/feed, not covered by current APIs.',unit:'MT'},
{metalSlug:'gold',metal:'Gold',category:'Precious metal',product:'Gold Bullion / Jewellery Scrap',commonGrades:['24K 999','22K 916','dore'],forms:['bar','coin','grain','jewellery scrap'],primaryUses:['jewellery','investment','refining'],buyerIndustries:['jewellery manufacturers','bullion dealers','refiners'],qualityChecks:['assay','KYC','purity','secure payment','GST'],searchTerms:['bullion dealers','gold refiners','jewellery manufacturers'],priceStatus:'api-live',pricingNote:'Spot gold API-live; physical trade requires dealer premium and assay.',unit:'KG'},
{metalSlug:'silver',metal:'Silver',category:'Precious/industrial metal',product:'Silver Bullion / Contacts / Brazing Alloy',commonGrades:['999','925','silver contacts'],forms:['bar','grain','contacts','brazing rod'],primaryUses:['jewellery','solar','electronics','brazing'],buyerIndustries:['jewellery makers','solar manufacturers','electronics recyclers','brazing alloy makers'],qualityChecks:['assay','purity','plated vs solid','dealer verification'],searchTerms:['silver bullion dealers','silver contacts buyers','silver brazing alloy manufacturers'],priceStatus:'api-live',pricingNote:'Spot silver API-live; physical price has premium/deduction.',unit:'KG'}
];

export const getProductsByMetal=(slug:string)=>metalProducts.filter(p=>p.metalSlug===slug);
export const priceStatusLabel:Record<LiveStatus,string>={
 'api-live':'API live base',
 'supplier-quote':'Supplier quote needed',
 'formula-estimate':'Formula estimate',
 'manual-market':'Manual market quote'
};
