import {NextRequest,NextResponse} from 'next/server';
import {csv} from '@/lib/marketplaceStore';
import {createLogisticsProvider,deleteLogisticsProvider,listLogisticsProviders,updateLogisticsProvider} from '@/lib/proDb';
import {sendOrQueueEmail} from '@/lib/email';
export const dynamic='force-dynamic';
const headers=['id','createdAt','status','companyName','contactName','phone','email','country','state','city','serviceTypes','specializations','capacityMt','baseRate','ratePerKm','ratePerMt','minimumCharge','contractStatus','paymentResponsibilityDefault'];
const arr=(v:any)=>Array.isArray(v)?v:String(v||'').split(',').map(x=>x.trim()).filter(Boolean);
function sanitize(body:any){return{id:body.id||`LGP-${Date.now()}`,createdAt:body.createdAt||new Date().toISOString(),status:body.status||'PENDING_CONTRACT',companyName:String(body.companyName||body.name||'').trim(),contactName:body.contactName||'',phone:body.phone||'',email:body.email||'',website:body.website||'',gstNumber:body.gstNumber||'',panNumber:body.panNumber||'',address:body.address||'',country:body.country||'India',state:body.state||'',city:body.city||'',nearbyCities:arr(body.nearbyCities),serviceableCountries:arr(body.serviceableCountries).length?arr(body.serviceableCountries):['India'],serviceableStates:arr(body.serviceableStates),serviceableCities:arr(body.serviceableCities),serviceTypes:arr(body.serviceTypes),specializations:arr(body.specializations),deliveryType:body.deliveryType||'Road transport',speed:body.speed||'Standard',capacityMt:Number(body.capacityMt||0),fleetSize:Number(body.fleetSize||0),availabilityDates:arr(body.availabilityDates),unavailableDates:arr(body.unavailableDates),baseRate:Number(body.baseRate||0),ratePerKm:Number(body.ratePerKm||0),ratePerMt:Number(body.ratePerMt||0),minimumCharge:Number(body.minimumCharge||0),loadingCharge:Number(body.loadingCharge||0),insurancePercent:Number(body.insurancePercent||0),fuelSurchargePercent:Number(body.fuelSurchargePercent||0),gstPercent:Number(body.gstPercent||0.18),contractStatus:body.contractStatus||'NOT_SENT',contractNotes:body.contractNotes||'',paymentResponsibilityDefault:['SELLER','SPLIT'].includes(String(body.paymentResponsibilityDefault||'').toUpperCase())?String(body.paymentResponsibilityDefault).toUpperCase():'BUYER',adminNotes:body.adminNotes||'',adminPricingLocked:true}}
function onboardingHtml(p:any){return `<div style="font-family:Arial,sans-serif;color:#0f172a;line-height:1.55"><h2>Talmech Logistics Vendor Onboarding</h2><p>Hello ${p.contactName||p.companyName},</p><p>Your logistics partner profile has been created in Talmech Trading admin for internal order coordination.</p><p><b>Contract onboarding required:</b> freight rate card, GST documents, PAN, insurance responsibility, vehicle documents, driver/KYC process, detention policy, damage/liability clauses, cancellation terms, confidentiality, payment cycle, dispute resolution and SLA acceptance must be completed before confirmed order assignment.</p><p><b>Talmech Trading</b><br/>Support: +91 7389642874</p></div>`}
export async function GET(req:NextRequest){const rows=await listLogisticsProviders();if(req.nextUrl.searchParams.get('format')==='csv')return new NextResponse(csv(rows,headers),{headers:{'content-type':'text/csv; charset=utf-8','content-disposition':'attachment; filename="talmech-logistics-providers.csv"'}});return NextResponse.json({ok:true,providers:rows,updatedAt:new Date().toISOString(),storage:process.env.DATABASE_URL?'database':'json-fallback'});}
export async function POST(req:NextRequest){const row=sanitize(await req.json());if(!row.companyName)return NextResponse.json({ok:false,error:'Company name is required.'},{status:400});const created=await createLogisticsProvider(row);if(row.email)await sendOrQueueEmail({to:row.email,subject:'Talmech Logistics Vendor Onboarding',html:onboardingHtml(row),leadId:row.id});return NextResponse.json({ok:true,provider:created,message:'Logistics provider created. Vendor confirmation email sent or queued.'});}
export async function PATCH(req:NextRequest){const body=await req.json();if(!body.id)return NextResponse.json({ok:false,error:'Provider id required.'},{status:400});const patch=sanitize({...body.patch,id:body.id,createdAt:undefined});delete(patch as any).id;delete(patch as any).createdAt;const updated=await updateLogisticsProvider(body.id,patch);return NextResponse.json({ok:Boolean(updated),provider:updated});}
export async function DELETE(req:NextRequest){const id=req.nextUrl.searchParams.get('id');if(!id)return NextResponse.json({ok:false,error:'Provider id required.'},{status:400});await deleteLogisticsProvider(id);return NextResponse.json({ok:true});}
